### ISSUE TITLE
Fails to recognize changed superclass

### ISSUE THREAD

**Issue by melix** [siom79/japicmp#11]
We have integrated `japicmp` into Groovy to integrate binary compatibility checks. See [1] and [2].

However, it fails to recognize the change of superclass. To reproduce:

```
git clone https://github.com/melix/japicmp-bugs.git
cd changed-superclass
./gradlew japicmp
```

The build should fail, but it doesn't, because japicmp failed to recognize the new superclass and says the class is unchanged.

[1] https://github.com/melix/japicmp-gradle-plugin
[2] https://github.com/groovy/groovy-core/commit/29e3bd4249bb3aa8fb110bb3b31fc68c9c042d39

**Comment by oliverburn** [comment]
I am still running into this bug with running against version 0.2.2.
