### ISSUE TITLE
Breaking build on Binary incompatibility doesn't seem to work

### ISSUE THREAD

**Issue by vmassol** [siom79/japicmp#111]
Hi there,

I searched for a mailing-list or forum for asking questions/discussing but couldn't find one so I'm reporting an issue here even though it could be just me not using japicmp correctly. I'm just discovering it today and I'm excited to try using it as a replacement of clirr for the xwiki open source project (http://xwiki.org).

I've tested the following config:

        <plugin>
          <groupId>com.github.siom79.japicmp</groupId>
          <artifactId>japicmp-maven-plugin</artifactId>
          <version>0.7.0</version>
          <configuration>
            <oldVersion>
              <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>${project.artifactId}</artifactId>
                <version>${xwiki.clirr.previous.version}</version>
              </dependency>
            </oldVersion>
            <newVersion>
              <file>
                <path>${project.build.directory}/${project.artifactId}-${project.version}.jar</path>
              </file>
            </newVersion>
            <parameter>
              <onlyModified>true</onlyModified>
              <accessModifier>protected</accessModifier>
              <breakBuildOnModifications>false</breakBuildOnModifications>
              <breakBuildOnBinaryIncompatibleModifications>true</breakBuildOnBinaryIncompatibleModifications>
              <onlyBinaryIncompatible>false</onlyBinaryIncompatible>
              <includeSynthetic>true</includeSynthetic>
              <ignoreMissingClasses>false</ignoreMissingClasses>
              <excludes>
                <exclude>*.internal.*</exclude>
              </excludes>
            </parameter>
          </configuration>
          <executions>
            <execution>
              <phase>verify</phase>
              <goals>
                <goal>cmp</goal>
              </goals>
            </execution>
          </executions>
        </plugin>

And it doesn't break on binary incompatible change. For example I get the following in the diff:

````
Comparing /Users/vmassol/.m2/repository/org/xwiki/commons/xwiki-commons-extension-api/7.4.1/xwiki-commons-extension-api-7.4.1.jar with /Users/vmassol/dev/xwiki/git/xwiki-commons/xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api/target/xwiki-commons-extension-api-8.0-SNAPSHOT.jar:
[...]
**** MODIFIED INTERFACE: PUBLIC ABSTRACT org.xwiki.extension.Extension  (not serializable)
        +++  NEW INTERFACE: java.lang.Comparable
        +++  NEW FIELD: PUBLIC(+) STATIC(+) FINAL(+) java.lang.String FIELD_ALLOWEDNAMESPACES
        +++  NEW FIELD: PUBLIC(+) STATIC(+) FINAL(+) java.lang.String FIELD_ALLOWEDNAMESPACE
        +++* NEW METHOD: PUBLIC(+) ABSTRACT(+) java.util.Collection getAllowedNamespaces()
        +++* NEW METHOD: PUBLIC(+) ABSTRACT(+) org.xwiki.extension.ExtensionId getExtensionFeature(java.lang.String)
        +++* NEW METHOD: PUBLIC(+) ABSTRACT(+) java.util.Collection getExtensionFeatures()
        ===  UNCHANGED METHOD: PUBLIC ABSTRACT java.util.Collection getFeatures()
                +++  NEW ANNOTATION: java.lang.Deprecated
[...]
`````

Adding a new method to an interface is a binary incompatibility for sure but the japicmp maven plugin doesn't break the build.

Any idea?

Thanks a lot

**Comment by vmassol** [comment]
I think I know why it doesn't break the build. https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html#jls-13.5 says that "Adding a method to an interface does not break compatibility with pre-existing binaries.".

In practice if some new code calls the new interface method, then old code compiled with the old interface will break at runtime with an AbstractMethodError. 

So I guess it all depends on the definition of binary compatibility. However for the XWiki project we do need to break on anything that will make old compiled code break at runtime.

Is that possible with japicmp?

Note that with CLIRR this was correctly reported as a 7012 error, see http://clirr.sourceforge.net/clirr-core/exegesis.html

Thanks

**Comment by siom79** [comment]
As you have already seen in the [JLS](https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html#jls-13.5), adding a method to an existing interface is not binary incompatible as there is no code that invokes the new method. But it is source incompatible, as you have to modify classes that implement this interface. You can therefore set the parameter `breakBuildOnSourceIncompatibleModifications` to true as described [here](http://siom79.github.io/japicmp/MavenPlugin.html).

The JLS defines "A change to a type is binary compatible with (equivalently, does not break binary compatibility with) pre-existing binaries if pre-existing binaries that previously linked without error will continue to link without error." This definition therefore assumes that you want to use the new version of a library with pre-existing binaries. In this case the "old" binary does not know about the new method of the interface and therefore does not invoke it.

**Comment by vmassol** [comment]
Thanks a lot for the explanation Martin. I'm now just realizing the difference between binary incompatibility and source incompatibility. It works fine with `breakBuildOnSourceIncompatibleModifications`
