### ISSUE TITLE
Problem understanding why build is breaking when new interface introduced

### ISSUE THREAD

**Issue by vmassol** [siom79/japicmp#113]
I'm trying to have the build fail when backward compatiblity is broken. However at the moment I have japicmp failing the build when new interfaces are added (I have source breakage on):

````
+++* NEW INTERFACE: PUBLIC(+) ABSTRACT(+) org.xwiki.component.namespace.NamespaceValidator  (not serializable)
        +++* NEW SUPERCLASS: java.lang.Object
        +++* NEW METHOD: PUBLIC(+) ABSTRACT(+) void checkAllowed(java.util.Collection, java.lang.String)
        +++* NEW METHOD: PUBLIC(+) ABSTRACT(+) boolean isAllowed(java.util.Collection, java.lang.String)
        +++  NEW ANNOTATION: org.xwiki.component.annotation.Role
````

This cannot be a backward incompatibility breakage since this is a new interface so there cannot be old code using it...

I don't understand why japicmp reports it as a source incompatibility.

Any idea?

Thanks!

**Comment by siom79** [comment]
This looks like a bug. A check that verifies if the interface itself is new seems to be missing.

I will fix it ASAP.

**Comment by vmassol** [comment]
ok great, thanks.

**Comment by siom79** [comment]
Fixed on the `develop` branch.

In case you want to try it out:
```
git clone https://github.com/siom79/japicmp.git
cd japicmp
git checkout develop
mvn install
```
