### ISSUE TITLE
source/binary compatibility check is broken

### ISSUE THREAD

**Issue by ironcream** [siom79/japicmp#114]
I believe this issue is related to #59 
Not only adding new method to an interface should be at least "source incompatible", but the same stands true for abstract base classes. 
This might happen directly as well as via hierarchy changes when `AbstractBaseClass` gets to extend some another `AbstractInsertedClass`, etc.

**For example:**
Imagine two versions of a class which go like that:
```
//v1
package superclass;
public abstract class AbstractBase
{
    public abstract void doBaseStuff();
}
```

```
//v2
package superclass;
public abstract class AbstractBase extends AbstractInserted //added extra things to implement
{
    public abstract void doBaseStuff();
}
```

Now the difference between japicmp 0.6.2 and 0.7.0 is the following

0.6.2 (detects "incompatibility", I'd call it desired behaviour):
```
final JApiClass c = jarArchiveComparator.compare(oldJar, newJar).get(0);
final JApiSuperclass s = c.getSuperclass();
System.out.println(c.isBinaryCompatible()); //<-- false
System.out.println(s.isBinaryCompatible()); //<-- false
```

0.7.0 (reports everything is compatible "binary" as well as "source". Shouldn't be like that):
```
final JApiClass c = jarArchiveComparator.compare(oldJar, newJar).get(0);
final JApiSuperclass s = c.getSuperclass();
System.out.println(c.isBinaryCompatible()); //<-- true!
System.out.println(c.isSourceCompatible()); //<-- true!
System.out.println(s.isBinaryCompatible()); //<-- true!
System.out.println(s.isSourceCompatible()); //<-- true!
```

**Comment by siom79** [comment]
Fixed this on the `develop` branch although the old behavior was not absolutely correct. Adding a new superclass is not binary compatible, even if we introduce new abstract methods through it. But introducing a new abstract method by adding a new superclass breaks of course source compatiblity as we are forced to implement it when we compile it.

**Comment by ironcream** [comment]
Will try from the develop branch, thanks.
