### ISSUE TITLE
[maven plugin] allow outputting "suggested" version to user defined property

### ISSUE THREAD

**Issue by esuomi** [siom79/japicmp#117]
I would like to be able to define a configuration property for the Maven plugin which would contain the name of the property which would contain the "suggested" version of the project after running the plugin.

As an example, if my previous project version is `1.3.0` and current changes in project code base are major breaking ones ([`VersionChange#MAJOR`](https://github.com/siom79/japicmp/blob/master/japicmp-maven-plugin/src/main/java/japicmp/maven/VersionChange.java#L17)), with the following (_example_) configuration somewhere in POM

``` xml
...
<plugin>
  <groupId>com.github.siom79.japicmp</groupId>
  <artifactId>japicmp-maven-plugin</artifactId>
  <configuration>
    <suggestedVersionProperty>versioning.suggestedVersion</suggestedVersionProperty>
    <!-- other configuration properties... -->
  </configuration>
</plugin>
...
```

would effectively run something like this

``` java
if (pluginParameters.getSuggestedVersionProperty() != null) {
  mavenProject.getProperties()
    .setProperty(pluginParameters.getSuggestedVersionProperty(),
                 versionChange.getSuggestedVersion());
}
```

somewhere around [here](https://github.com/siom79/japicmp/blob/master/japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java#L99-L116) and set `versioning.suggestedVersion` property to `2.0.0`.

---

What I am trying to accomplish is to build a parent POM configuration which allows me to use simply `LATEST-SNAPSHOT` as current version for my projects, run this plugin (conditionally) against last known published version and produce a suggested version for the current project. I hope this makes sense, please ask for clarifications if any are needed.

**Comment by siom79** [comment]
Why do you want to have a property set? 

While thinking about a possible implementation I stumbled about the point that you can specify multiple artifacts as old or new version (see for example [here](http://siom79.github.io/japicmp/MavenPlugin.html#Site_report)). You would then also need multiple properties...?
