### ISSUE TITLE
japicmp-testbase / MethodsTest#testReturnValueStringToInt() is probably broken

### ISSUE THREAD

**Issue by esuomi** [siom79/japicmp#118]
Test [`MethodsTest#testReturnValueStringToInt()`](https://github.com/siom79/japicmp/commit/f170325504235dcbaebe9acfe4e0c9d25fa1f85f#L27-L47) doesn't really do anything as `jApiMethod.getReturnType()` never returns a `java.lang.String` and thus all branches always evaluate to `false` and nothing gets tested. This probably got broken by [this commit](https://github.com/siom79/japicmp/commit/403814628f9e6f7ecfe570fb9ffbbf28c35a69c5) although I'm not 100% sure as I only took a cursory glance why this is the way it is.

**Comment by siom79** [comment]
Thanks for reporting this.

In older versions of japicmp the method `JApiMethod.getReturnType()` just returned a `java.lang.String`. Back then the comparison using `equals` was ok. Meanwhile this method returns a domain object and no longer a string, hence the tests did not fail but did not test wthat they were supposed to do.

I fixed this on the `develop` branch.
