### ISSUE TITLE
Interface changing from being implemented directly to indirectly should not be flagged as deleted

### ISSUE THREAD

**Issue by gunnarmorling** [siom79/japicmp#119]
Thanks for this nice tool! The generated report is very useful, I noticed one issue only.

Let this be my hierarchy in the previous release:

    interface SomeInterface {}

    class SomeClass implements SomeInterface {}

And that's my hierarchy in the new release:

    interface SomeInterface {}

    interface AnotherInterface extends SomeInterface {}

    class SomeClass implements AnotherInterface {}

Then the report will incorrectly state that `SomeInterface` has been removed from the set of interfaces implemented by `SomeClass`.

**Comment by siom79** [comment]
Fixed on `develop` branch.

**Comment by gunnarmorling** [comment]
Thanks, that was quick. Appreciated very much!
