### ISSUE TITLE
Fails to recognize changed interfaces

### ISSUE THREAD

**Issue by melix** [siom79/japicmp#12]
We have integrated `japicmp` into Groovy to integrate binary compatibility checks. See [1] and [2].

However, it fails to recognize the change in implemented interfaces. To reproduce:

```
git clone https://github.com/melix/japicmp-bugs.git
cd changed-interface
./gradlew japicmp
```

The build should fail, but it doesn't, because japicmp failed to recognize the new interface and says the class is unchanged.

[1] https://github.com/melix/japicmp-gradle-plugin
[2] https://github.com/groovy/groovy-core/commit/29e3bd4249bb3aa8fb110bb3b31fc68c9c042d39

**Comment by oliverburn** [comment]
I am still running into this bug when running against version 0.2.2.

**Comment by siom79** [comment]
One of the unit tests is concerned with interface changes. You can find it [here](https://github.com/siom79/japicmp/blob/development/japicmp-testbase/japicmp-test/src/test/java/japicmp/test/IntefacesTest.java). It also covers the case that an interface is added to a class.

How do you test for interface changes?

Your code could look like this:

    JarArchiveComparator jarArchiveComparator = new JarArchiveComparator(new JarArchiveComparatorOptions());
    List<JApiClass> jApiClasses = jarArchiveComparator.compare(getArchive("japicmp-test-v1.jar"), getArchive("japicmp-test-v2.jar"));
    for (JApiClass jApiClass : jApiClasses) {
        assertThat(jApiClass.getChangeStatus(), is(JApiChangeStatus.MODIFIED)); //check that class is flagged as modified
        List<JApiImplementedInterface> interfaces = jApiClass.getInterfaces();
        for (JApiImplementedInterface jApiImplementedInterface : interfaces) {
            assertThat(jApiImplementedInterface.getChangeStatus(), is(JApiChangeStatus.MODIFIED)); // check that each implemented interface is flagged as modified
        }
    }

**Comment by oliverburn** [comment]
I have created a [repository](https://bitbucket.org/ojburn/japicmp-bugs/overview) for demonstrating the problems I am seeing. To reproduce:

    git clone https://ojburn@bitbucket.org/ojburn/japicmp-bugs.git
    cd japicmp-bugs/missed-changes
    ./gradlew jar cmp

The interfaces changes missed are:

- Adding from [v1](https://bitbucket.org/ojburn/japicmp-bugs/src/15b05f584cac17a3e6d894eab17672841b0ec09d/missed-changes/v1/src/main/java/samples/InterfaceAdded.java?at=master) to [v2](https://bitbucket.org/ojburn/japicmp-bugs/src/15b05f584cac17a3e6d894eab17672841b0ec09d/missed-changes/v2/src/main/java/samples/InterfaceAdded.java?at=master)
- Removing from [v1](https://bitbucket.org/ojburn/japicmp-bugs/src/15b05f584cac17a3e6d894eab17672841b0ec09d/missed-changes/v1/src/main/java/samples/InterfaceRemoved.java?at=master) to [v2](https://bitbucket.org/ojburn/japicmp-bugs/src/15b05f584cac17a3e6d894eab17672841b0ec09d/missed-changes/v2/src/main/java/samples/InterfaceRemoved.java?at=master)

Note: there are also a number of other tests that japicmp does not detect.

**Comment by siom79** [comment]
Thank you for setting up a repository. Now I could reproduce the problem and fixed it on the new branch [missed-changes](https://github.com/siom79/japicmp/tree/missed-changes).

Running your code with version 0.2.3-SNAPSHOT from the branch missed-changes results in the following output:

```
:cmp:compileJava
:cmp:processResources UP-TO-DATE
:cmp:classes
:cmp:jar
:v1:compileJava
:v1:processResources UP-TO-DATE
:v1:classes
:v1:jar UP-TO-DATE
:v2:compileJava
:v2:processResources UP-TO-DATE
:v2:classes
:v2:jar UP-TO-DATE
:cmp
[ant:concat] Args:
[ant:concat] arg[0] = v1/build/libs/v1-1.0.jar
[ant:concat] arg[1] = v2/build/libs/v2-1.0.jar
[ant:concat]
[ant:concat] Processing samples.FieldChanges, change status MODIFIED
[ant:concat]    Superclass change status UNCHANGED
[ant:concat]    Number interfaces: 0
[ant:concat]    Number methods: 0
[ant:concat]
[ant:concat] Processing samples.SuperclassAdded, change status MODIFIED
[ant:concat]    Superclass change status MODIFIED
[ant:concat]    Number interfaces: 0
[ant:concat]    Number methods: 0
[ant:concat]
[ant:concat] Processing samples.InterfaceMethodChanges, change status MODIFIED
[ant:concat]    Superclass change status UNCHANGED
[ant:concat]    Number interfaces: 0
[ant:concat]    Number methods: 13
[ant:concat]    method paramChangedIntToString, change status REMOVED
[ant:concat]    method publicRemoved, change status UNCHANGED
[ant:concat]    method paramAdded, change status REMOVED
[ant:concat]    method paramRemoved, change status REMOVED
[ant:concat]    method returnChangedIntToVoid, change status REMOVED
[ant:concat]    method returnChangedStringToObject, change status REMOVED
[ant:concat]    method returnChangedVoidToInt, change status REMOVED
[ant:concat]    method paramRemoved, change status NEW
[ant:concat]    method paramAdded, change status NEW
[ant:concat]    method returnChangedIntToVoid, change status NEW
[ant:concat]    method paramChangedIntToString, change status NEW
[ant:concat]    method returnChangedStringToObject, change status NEW
[ant:concat]    method returnChangedVoidToInt, change status NEW
[ant:concat]
[ant:concat] Processing samples.InterfaceRemoved, change status MODIFIED
[ant:concat]    Superclass change status UNCHANGED
[ant:concat]    Number interfaces: 1
[ant:concat]    interface java.lang.Comparable, change status REMOVED
[ant:concat]    Number methods: 2
[ant:concat]    method compareTo, change status REMOVED
[ant:concat]    method compareTo, change status UNCHANGED
[ant:concat]
[ant:concat] Processing samples.InterfaceAdded, change status MODIFIED
[ant:concat]    Superclass change status UNCHANGED
[ant:concat]    Number interfaces: 1
[ant:concat]    interface java.io.Serializable, change status NEW
[ant:concat]    Number methods: 0

BUILD SUCCESSFUL

Total time: 15.234 secs
```

The class SuperclassAdded is now reported as `MODIFIED`, the removed Interface `Comparable` is also reported.

Can you confirm that?

As I have not yet published the snapshot:
```
git clone https://github.com/siom79/japicmp.git
cd japicmp/
git checkout missed-changes
mvn clean install
```
(Please use JDK 1.8, for older versions please uncomment the javadoc parameter -Xdoclint:none in the base pom.xml).

The underlying problem was, that per default the system class path was not added to the javassist class pool. Now this is done and japicmp can find classes from the JDK (like Serializable and ArithmeticException).

You mentioned that there are other changes that have not been detected. What changes are these?  Please note that all interface methods are public, hence removing the public modifier in the source file is not a change in the class file.

**Comment by oliverburn** [comment]
Thanks, I can confirm that the `0.2.3-SNAPSHOT` based on the branch correctly detects the interface changes.
I'll raise a separate issue for the other changes incorrectly reported.
