### ISSUE TITLE
Feature Request: to be able to ignore certain missing classes

### ISSUE THREAD

**Issue by davidyan74** [siom79/japicmp#124]
Currently the ignoreMissingClasses feature is a true or false -- either you ignore all missing classes or you don't.  How about a feature that allows missing classes that belong to certain packages, or classes whose names match a regexp?

**Comment by siom79** [comment]
On the `develop` branch I have added a new configuration option named `<ignoreMissingClassesByRegularExpressions/>` that allows you to ingore classes by a regular expression.

If you like, you can try it out:
```
git clone https://github.com/siom79/japicmp.git
cd japicmp
git checkout develop
mvn clean install
```

**Comment by jglick** [comment]
Is this not resolved?

**Comment by siom79** [comment]
According to the documentation this is resolved. ;)
