### ISSUE TITLE
skipPomModules/packagingSupporteds not working

### ISSUE THREAD

**Issue by gunnarmorling** [siom79/japicmp#128]
I'd like to configure japicmp in the root POM of my multi-module Maven project. Of course, no report is needed for the root module itself. Two settings seem to be provided to help with that:

    skipPomModules>true</skipPomModules>
    <packagingSupporteds>
        <packagingSupported>jar</packagingSupported>
    </packagingSupporteds

Unfortunately though, both don't take any affect, i.e. the plug-in is still run for the root module, resulting in an exception about the JAR file of that module missing (which is natural, as it has POM packaging). I took a quick look in the debugger and the `mavenProject` injected into the Mojo is `null`, resulting in an early return from the filter method.

Any idea why that could be the case?

**Comment by siom79** [comment]
`mavenProject` is injected by the container, so I don't know why it should be `null`.

Which maven version are you using? Is there an example that reproduces this behavior?

**Comment by siom79** [comment]
Cannot reproduce.

**Comment by gunnarmorling** [comment]
Sorry for the radio silence, kind of forgot about this one.

I'm on Maven 3.3.3 @ OS X. That's the project where I noticed this behavior: https://github.com/hibernate/hibernate-search/blob/master/pom.xml.

**Comment by siom79** [comment]
Could reproduce with Maven 3.3.3 @ Ubuntu 14.04. You defined the plugin within the `<reporting/>` block of the root pom with packaging type `pom`. In this case the injected value for `mavenProject` was not properly propagated. Fixed this on the `develop` branch.
