### ISSUE TITLE
Enum serialVersionUID change should not report as incompatible

### ISSUE THREAD

**Issue by granthenke** [siom79/japicmp#131]
If you add a value to an Enum japicmp will report:
> MODIFIED (Serializable incompatible(!): default serialVersionUID changed)

According to the serialization spec (http://docs.oracle.com/javase/8/docs/platform/serialization/spec/serial-arch.html#a6469) the serialization of Enums is a special case and does not leverage the serialVersionUID:
> Enum constants are serialized differently than ordinary serializable or externalizable objects. The serialized form of an enum constant consists solely of its name; field values of the constant are not present in the form....
> Similarly, any serialPersistentFields or serialVersionUID field declarations are also ignored--all enum types have a fixed serialVersionUID of 0L.

**Comment by siom79** [comment]
serialVersionUID is ignored for enums.
