### ISSUE TITLE
Introduction of a super class that implements an interface should not be binary incompatible

### ISSUE THREAD

**Issue by vrozov** [siom79/japicmp#133]
As long as a set of interfaces implemented by a class does not change, whether class implements interface directly or it extends from existing or newly introduced super class that implements the interface, the binary compatibility is preserved.

**Comment by siom79** [comment]
Do you have a concrete example? Which version are you using?

I have tested it with a class that implements an interface `I` and then in the new version extends a superclass `S` that implements `I` while the class itself no longer implements the interface. The flag binary compatible was set to `true`.

**Comment by vrozov** [comment]
Please check https://github.com/DataTorrent/Netlet/pull/51. In the site report, `AbstractClient` is marked as `MODIFIED (!)` due to removal of a protected field and an introduction of a superclass.

**Comment by siom79** [comment]
I have checked your changes on your pull request with version `0.8.1-SNAPSHOT` including my changes from yesterday and it worked fine. Hence I think that the two tickets #132 and #133 had the same root cause.
```
<plugin>
        <groupId>com.github.siom79.japicmp</groupId>
        <artifactId>japicmp-maven-plugin</artifactId>
        <version>0.8.1-SNAPSHOT</version>
        ...
</plugin>
```
