### ISSUE TITLE
Feature request: possibility to compare static blocks

### ISSUE THREAD

**Issue by greexon** [siom79/japicmp#135]
I have the following code:

```
static {
    configure("test");
}
```

Then I have the next code:
```
static {
    configure("test2");
}
```

It's required to track difference between these two blocks of code.

**Comment by siom79** [comment]
This has nothing to do with binary or source compatibility. Tracking changes of behavior is not supported (and beyond that a [NP-complete](https://en.m.wikipedia.org/wiki/NP-completeness) problem).
