### ISSUE TITLE
Can't use report for all kinds of Maven projects

### ISSUE THREAD

**Issue by cristalp** [siom79/japicmp#137]
First, let me congratulate you for this very cool product!

Unfortunately, I have a problem with my Maven site. I have a parent POM where everything is configured, including site reports. I don't want to change it for every kind of Maven project type (packaging), besides (as far as I know) it's not possible either.

So, I have my site configuration:
```
                <plugin>
                  <groupId>com.github.siom79.japicmp</groupId>
                  <artifactId>japicmp-maven-plugin</artifactId>
                  <reportSets>
                    <reportSet>
                      <reports>
                        <report>cmp-report</report>
                      </reports>
                    </reportSet>
                  </reportSets>
                  <configuration>
                    <oldVersion>
                      <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>${project.artifactId}</artifactId>
                        <version>RELEASE</version>
                        <type>${project.packaging}</type>
                      </dependency>
                    </oldVersion>
                    <newVersion>
                      <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>${project.artifactId}</artifactId>
                        <version>LATEST</version>
                        <type>${project.packaging}</type>
                      </dependency>
                    </newVersion>
                    <parameter>
                      <onlyModified>true</onlyModified>
                      <breakBuildBasedOnSemanticVersioning>false</breakBuildBasedOnSemanticVersioning>
                      <htmlTitle>${project.artifactId} compatibility</htmlTitle>
                      <ignoreMissingClasses>true</ignoreMissingClasses>
                      <ignoreNonResolvableArtifacts>true</ignoreNonResolvableArtifacts>
                      <ignoreMissingOldVersion>true</ignoreMissingOldVersion>
                      <packagingSupporteds>
                        <packagingSupported>jar</packagingSupported>
                        <packagingSupported>ejb</packagingSupported>
                      </packagingSupporteds>
                    </parameter>
                  </configuration>
                </plugin>
```

We use the ejb packaging a lot for our API modules. As a dependency, however, it's still a JAR.

So, I want to run the site for a whole Maven project with several modules, but it breaks with the following error:

     [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project foo: Error during page generation: Error rendering Maven report: Failed to generate report: Processing of jar file C:\...\1.14.0\foo-domain-1.14.0.pom failed: error in opening zip file -> [Help 1]

What am I doing wrong?

**Comment by siom79** [comment]
Thanks for the nice words. :blush:

Your configuration looks good. I have setup a simple test project with two sub modules, one normal jar module and one `ejb` module:
```
[INFO] test ............................................... SUCCESS [  0.176 s]
[INFO] ejb-module ......................................... SUCCESS [  0.776 s]
[INFO] jar-module ......................................... SUCCESS [  0.114 s]
```
The configuration of japicmp looked like this:
```
<plugin>
                <groupId>com.github.siom79.japicmp</groupId>
                <artifactId>japicmp-maven-plugin</artifactId>
                <version>0.8.2-SNAPSHOT</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>cmp-report</report>
                        </reports>
                    </reportSet>
                </reportSets>
                <configuration>
                    <newVersion>
                        <dependency>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                            <version>LATEST</version>
                            <type>${project.packaging}</type>
                        </dependency>
                    </newVersion>
                    <parameter>
                        <packagingSupporteds>
                            <packagingSupported>jar</packagingSupported>
                            <packagingSupported>ejb</packagingSupported>
                        </packagingSupporteds>
                    </parameter>
                </configuration>
            </plugin>
```
I have left out the declaration of `<oldVersion/>` as it is automatically detected. As the output above suggests I could not reproduce the issue with `mvn site:site site:stage`.

But while searching for the issue I found that the detection of the new version could be [improved](https://github.com/siom79/japicmp/commit/2d1c47c875e231402a0c7732b983aebf13867364). :smirk: 

Have you tried to set the new version directly like below?
```
<newVersion>
    <file>
        <path>${project.build.directory}/${project.artifactId}-${project.version}.jar</path>
    </file>
</newVersion>
```
Please note that the above declaration sets the file extension directly to `jar` instead of using `${project.packaging}` as the latter would be `ejb` in EJB projects. If `jar` does not fit in all modules you could introduce a property that is overwritten in the corresponding modules.

**Comment by cristalp** [comment]
The problem with the last suggestion is that I'm just using `mvn clean site`, so I don't have a JAR in the `target` directory.

But if I understand your improvement right, the plugin should now look for `ejb` artifacts itself, right?

Are the SNAPSHOTs available somewhere or is the release 0.8.2 already planned?

**Comment by siom79** [comment]
The improvement I have committed yesterday is concerned with the case that you don't provide the new version (and it is auto-detected). But your case should work as I have seen yesterday in my test project with an ejb submodule.

What surprises me regarding your error message is that the plugin tries to open a pom file as zip archive. That means it thinks that th module produces a jar/zip but the file is actually a pom. As pom modules are normally skipped (have you tried the option `skipPomModules`?) this could indicate a problem with your build. Is your project somewhere accessible? 

What surprises me is that accord

**Comment by cristalp** [comment]
Ok, I now upgraded to 0.8.1 and used the following configuration
```
                <plugin>
                  <groupId>com.github.siom79.japicmp</groupId>
                  <artifactId>japicmp-maven-plugin</artifactId>
                  <reportSets>
                    <reportSet>
                      <reports>
                        <report>cmp-report</report>
                      </reports>
                    </reportSet>
                  </reportSets>
                  <configuration>
                    <newVersion>
                      <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>${project.artifactId}</artifactId>
                        <version>LATEST</version>
                        <type>${project.packaging}</type>
                      </dependency>
                    </newVersion>
                    <parameter>
                      <onlyModified>true</onlyModified>
                      <breakBuildBasedOnSemanticVersioning>false</breakBuildBasedOnSemanticVersioning>
                      <htmlTitle>${project.artifactId} compatibility</htmlTitle>
                      <ignoreMissingClasses>true</ignoreMissingClasses>
                      <ignoreNonResolvableArtifacts>true</ignoreNonResolvableArtifacts>
                      <ignoreMissingOldVersion>true</ignoreMissingOldVersion>
                      <skipPomModules>true</skipPomModules>
                      <packagingSupporteds>
                        <packagingSupported>jar</packagingSupported>
                        <packagingSupported>ejb</packagingSupported>
                      </packagingSupporteds>
                    </parameter>
                  </configuration>
                </plugin>
```

That works on my local machine, and I'll try it on our build server as well.

By the way, I'll be on vacation the next two weeks. So thanks in the meantime, and I'll keep you informed.

**Comment by cristalp** [comment]
Ok, this works well on the build server.
Thanks for your help!

But I have a tiny suggestion for the Maven site report: The title `japicmp-maven-plugin` in the navigation (on the left side) is not very descriptive for anyone who doesn't know about japicmp. I'd suggest something like `Compatibility report`. Or the `htmlTitle` could be used.
