### ISSUE TITLE
Readme should link to other documentation

### ISSUE THREAD

**Issue by cowwoc** [siom79/japicmp#138]
readme.md hints that there is other documentation (e.g. the Maven plugin documentation says "see documentation" for a list of parameters) but never links to it.

Please add the appropriate links to the documentation found at https://github.com/siom79/japicmp/tree/master/src/site/markdown

For example, the section on the Maven plugin should link to the Maven-specific documentation.

**Comment by siom79** [comment]
The documentation can be found on the [website](http://siom79.github.io/japicmp/), which is linked from the README.MD. But I can add an additional link below the two examples there.

**Comment by cowwoc** [comment]
Oh. I totally missed that link. I landed on your Github page first, not realizing that the website even existed.

In the case, can you please rename the section header from "Website" to "Website / Documentation" or otherwise highlight that users should go to the website for further documentation?

**Comment by siom79** [comment]
Moved link to the website to the very beginning of the README.md file (on `develop` branch).
