### ISSUE TITLE
Changing a method parameter type to its super type

### ISSUE THREAD

**Issue by runeflobakk** [siom79/japicmp#142]
I have a question regarding compatibility on changing the type of a method parameter to one of it's super types. 

I have configured the japicmp-maven-plugin like this:
```xml
<onlyModified>true</onlyModified>
<onlyBinaryIncompatible>true</onlyBinaryIncompatible>
```
and when I change a method to accept a supertype of the parameter type for the method of the previous version, japicmp reports the method as `REMOVED (!)`. Which is true in some sense, as the original method signature is replaced with a method which takes a less specific supertype of the same argument.

Say I have
```java
interface A {}
interface B extends A {}

interface C {
    void accept(B arg);
}
```
and I change `void accept(B arg)` to `void accept(A arg)`, japicmp reports `void accept(B arg)` as `REMOVED (!)`, even though existing invocations passing `B`s should work just fine with `void accept(A arg)`.

Is this expected behaviour, or should such a change be considered compatible? Intuitively, I am thinking that accepting a less specific type than before should not introduce any compatibility problems, as the new signature should work with any existing use of the method, but there may be subtleties I am not aware of.

And thank you for a _very_ useful tool!

**Comment by siom79** [comment]
Chapter 13 ("Binary Compatibility") of the "Java Language Specification" states in section [13.4.14](https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html#jls-13.4.14):

"Changing the name of a method, or the type of a formal parameter to a method or constructor, or adding a parameter to or deleting a parameter from a method or constructor declaration creates a method or constructor with a new signature, and has the combined effect of deleting the method or constructor with the old signature and adding a method or constructor with the new signature."

This explains why changing the type of a formal parameter (even if it changes from subclass to its superclass) is like removing the old method and adding a new one.

Beyond that, trying to change the type of a parameter from the subclass to its superclass and invoking the method with an instance of the subclass will create a reference to the specific method in the class file and at runtime a `NoSuchMethodError`:

Version 1
```
	public static class MySuperclass {

	}

	public static class MySubclass extends MySuperclass {

	}

	public void method(MySubclass arg) {

	}
```
Version 2:
```
	public static class MySuperclass {

	}

	public static class MySubclass extends MySuperclass {

	}

	public void method(MySuperclass arg) {

	}
```
At runtime:
```
Exception in thread "main" java.lang.NoSuchMethodError: japicmp.test.Methods.method(Ljapicmp/test/Methods$MySubclass;)V
	at japicmp.test.client.JApiCmpClient.run(JApiCmpClient.java:20)
	at japicmp.test.client.JApiCmpClient.main(JApiCmpClient.java:13)
```

**Comment by runeflobakk** [comment]
Thank you for the explanation!
