### ISSUE TITLE
Ability to <include> a package without nested packages

### ISSUE THREAD

**Issue by cowwoc** [siom79/japicmp#150]
Currently, including a package using `<include>` results in all its sub-packages getting included as well.

Please provide a mechanism to include a package without its nested sub-packages. I want to build a whitelist of public packages for my API. The fact that a fixed configuration could silently match other packages in the future makes it fragile for my use-case.

**Comment by siom79** [comment]
Have you tried to exclude the inner sub-packages? Excludes are evaluated first, hence if you exclude the sub-package and include the outer parent package it should work.

**Comment by cowwoc** [comment]
Sorry, my description was misleading. When I talked about nested sub-packages, I meant simply sub-packages. Meaning, I want to be able to `<include>foobar</include>` without japicmp automatically including `<include>foobar.newpackage</include>` which may get added in the future without me noticing.

Upon further reflection though, this isn't so much of a big deal for a tool like japicmp (worse case scenario the build breaks when it shouldn't, I notice and fix it). I was hoping to perhaps say:

`<include>foobar</include>` should include `foobar` without any sub-packages
`<include>foobar.*</include>` should include `foobar` and a single level of sub-packages
`<include>foobar.**</include>` should include `foobar` and multiple levels of sub-packages

But I understand that this breaks backwards-compatibility so you can't just throw that in. Feel free to close this issue if you feel it is too much effort.

**Comment by siom79** [comment]
Has been implemente with #173
