### ISSUE TITLE
Old version is not ignored when <oldVersion> doesn't exist

### ISSUE THREAD

**Issue by cristalp** [siom79/japicmp#153]
This is my configuration:

      <plugin>
        <groupId>com.github.siom79.japicmp</groupId>
        <artifactId>japicmp-maven-plugin</artifactId>
        <version>0.9.2</version>
        <configuration>
          <skip>${skip.api-compatibility.check}</skip>
          <newVersion>
            <file>
              <path>${project.build.directory}/${project.artifactId}-${project.version}.jar</path>
            </file>
          </newVersion>
          <parameter>
            <onlyModified>true</onlyModified>
            <breakBuildOnBinaryIncompatibleModifications>true</breakBuildOnBinaryIncompatibleModifications>
            <breakBuildBasedOnSemanticVersioning>true</breakBuildBasedOnSemanticVersioning>
            <onlyBinaryIncompatible>true</onlyBinaryIncompatible>
            <ignoreMissingClasses>true</ignoreMissingClasses>
            <skipPomModules>true</skipPomModules>
            <noAnnotations>false</noAnnotations>
            <ignoreNonResolvableArtifacts>false</ignoreNonResolvableArtifacts>
            <ignoreMissingOldVersion>true</ignoreMissingOldVersion>
            <ignoreMissingNewVersion>true</ignoreMissingNewVersion>
            <packagingSupporteds>
              <packagingSupported>jar</packagingSupported>
              <packagingSupported>ejb</packagingSupported>
            </packagingSupporteds>
            <reportOnlyFilename>false</reportOnlyFilename>
            <skipXmlReport>true</skipXmlReport>
            <skipHtmlReport>true</skipHtmlReport>
            <skipDiffReport>true</skipDiffReport>
          </parameter>
        </configuration>
        <executions>
          <execution>
            <id>check-api-compatibility-for-semantic-versioning</id>
            <phase>package</phase>
            <goals>
              <goal>cmp</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

We have some Maven modules that we've started writing. There is no released version, and we're on version 1.0.0-SNAPSHOT.

The way I understand it is that the plugin looks in the Maven repo for the latest released version if I don't specify an <oldVersion>. And then I would expect ignoreMissingOldVersion=true to completely skip that and to ignore everything when there's no old version.

However, I get the following error:
[INFO] --- japicmp-maven-plugin:0.9.2:cmp (check-api-compatibility-for-semantic-versioning) @ foo-api ---
[INFO] artifact com.example:foo-api: checking for updates from repository.central
[INFO] Unable to find a previous version of the project in the repository.
[WARNING] Please provide at least one resolvable old version using one of the configuration elements <oldVersion/> or <oldVersions/>.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.431 s
[INFO] Finished at: 2016-11-17T15:19:27+01:00
[INFO] Final Memory: 66M/894M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.9.2:cmp (check-api-compatibility-for-semantic-versioning) on project foo-api: Please provide at least one old version. -> [Help 1]

If I understand the configuration correctly, this looks like a bug to me...
The only option I have at the moment is to skip the plugin (thanks for that possibility!).

**Comment by siom79** [comment]
The option `ignoreMissingOldVersion` is meant for the case that you specify an old version (which you did not) and this old version does not exist. This is helpful when inheriting the plugin from a base pom to the children and some children are new in the current version.

 When you leave out the `oldVersion` then the plugin tries to resolve the old version automatically. As this old version does not exist, you get the error. I think this behavior is correct, because comparing a current version with a non-existing version does not make sense and just skipping the execution might lead to wrong results.

So if you still want to use the plugin without having an old version, try to specify one with `<oldVersion/>` and then `ignoreMissingOldVersion` should ignore it.

But I think it may make sense for future versions of japicmp to also ignore missing old versions in the case the plugin automatically searches for them.

**Comment by cristalp** [comment]
Yes, exactly  :-)
Thanks for adding this.

**Comment by siom79** [comment]
Will be published with next release.
