### ISSUE TITLE
Enhancement: Includes and Excludes on a Maven Module base

### ISSUE THREAD

**Issue by cristalp** [siom79/japicmp#154]
For every project (for instance foo), we usually have a couple of Maven modules, like

- foo-api
- foo-impl
- foo-test

The only one relevant for API compatibility is foo-api, the others can be ignored.
But doing that with includes/excludes of packages would result in a huge list.

Having regular expressions in those includes/excludes would already be great.

But in my opinion there should be a new `includeModules` and `excludeModules` with regular expressions. At the moment, I'm only doing reports for that kind of projects, but I'm using `find` to get the includes in a bash script.

In my case for instance:

    <includeModules>
      <includeModule>.*-api</includeModule>
      <includeModule>util-.*</includeModule>
      <includeModule>.*-web-service</includeModule>
    </includeModules>

By the way: There's a typo on https://siom79.github.io/japicmp/MavenPlugin.html : The last include is written as `<inclue>`

**Comment by siom79** [comment]
Have you tried to use the option `<skip/>` with a property specified in the parent pom, which is then set to `true` in your impl and test modules?

**Comment by cristalp** [comment]
Yes, that's what I'm doing right now. But it's cumbersome because every time someone creates a project, I have to be informed and add the Maven property.

Doing it in a generic way would be easier.

**Comment by siom79** [comment]
OK, you have convinced me. I have just added this on the `develop` branch. It will be published with the next release.

**Comment by cristalp** [comment]
Great, thanks a lot!  :-)
