### ISSUE TITLE
support multi thread build

### ISSUE THREAD

**Issue by thomasmey** [siom79/japicmp#158]
building a project with -T 1C results in this warning:

[DEBUG] =======================================================================
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following goals are not marked @threadSafe in Apache Commons Compress:
[WARNING] com.github.siom79.japicmp:japicmp-maven-plugin:0.9.3:cmp
[WARNING] *****************************************************************
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1, ConflictMarker.markTime=1, ConflictMarker.nodeCount=22, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=7, ConflictIdSorter.conflictIdCount=12, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=6, ConflictResolver.conflictItemCount=20, DefaultDependencyCollector.collectTime=536, DefaultDependencyCollector.transformTime=19}
[DEBUG] org.apache.commons:commons-compress:jar:1.14-COMPRESS207
[DEBUG]    junit:junit:jar:4.12:test
[DEBUG]       org.hamcrest:hamcrest-core:jar:1.3:test
[DEBUG]    org.tukaani:xz:jar:1.6:compile
[DEBUG]    org.powermock:powermock-module-junit4:jar:1.6.4:test
[DEBUG]       org.powermock:powermock-module-junit4-common:jar:1.6.4:test
[DEBUG]          org.powermock:powermock-core:jar:1.6.4:test
[DEBUG]             org.javassist:javassist:jar:3.20.0-GA:test
[DEBUG]          org.powermock:powermock-reflect:jar:1.6.4:test
[DEBUG]    org.powermock:powermock-api-mockito:jar:1.6.4:test
[DEBUG]       org.mockito:mockito-core:jar:1.10.19:test
[DEBUG]          org.objenesis:objenesis:jar:2.1:test
[DEBUG]       org.powermock:powermock-api-support:jar:1.6.4:test

**Comment by siom79** [comment]
The plugin was already threadsafe, it was only missing the flag `threadSafe=true` in the `@Mojo` annotation.

Committed to the `master` branch. Will be released with 0.9.4.

**Comment by siom79** [comment]
Released with 0.9.4.
