### ISSUE TITLE
filterSnapshots method in JApiCmpMojo.java fails sometimes

### ISSUE THREAD

**Issue by mischor** [siom79/japicmp#160]
The filterSnapshot method filters using the predicate "SNAPSHOT".equals(version.getQualifier().
I have a project which has a version 3.0.0-alpha02-SNAPSHOT.  I think that the version.getQualifier() returns everything after the first dash.  Which doesn't equal SNAPSHOT, so the test fails.

Please change this test to something like:

String qualifier = version.getQualifier();
if (qualifier != null && qualifier.endsWith("SNAPSHOT") {
   versionIterator.remove();
}

**Comment by siom79** [comment]
I have changed the method `JApiCmpMojo.filterSnapshot()` to fit to your requirements.

It will be released with 0.9.4.

**Comment by siom79** [comment]
Released with 0.9.4.
