### ISSUE TITLE
[maven plugin] Comparing a library with itself fails

### ISSUE THREAD

**Issue by io7m** [siom79/japicmp#162]
Hello.

See the following repro case:

https://github.com/io7m/japicmp-bug-20170302

Comparing two identical versions of the same library erroneously fails.

**Comment by io7m** [comment]
_Why would anybody do this?!_

... I hear you cry!

The reason I ran into this was that I was looking to start enforcing semantic versioning on my own projects after having done it manually for years. I tried adding the plugin to a new project for experimentation, and as I hadn't published any version of the project yet, I set the new and old versions to the same value (which should presumably always pass the compatibility check).

If there's a preferred way to handle the case of there being no pre-existing versions of a library, I'm open to suggestions.

**Comment by io7m** [comment]
After having a look through the `japicmp` sources, it seems that this might be triggered by the fact that the project is version `0.1.0` but `japicmp` falls back to suggesting `0.0.1` as the version number. Making the project version `0.0.1` (or `0.0.2`, for that matter) works without issue.

I guess the real problem in this case is the lack of a good error report.

**Comment by io7m** [comment]
Haha, and I see from your commit that you probably agree!

Good timing there.

👍

**Comment by siom79** [comment]
Indeed, that is what I cried out. :smirk: 

The problem was that the `SemverOut` class returned the semantic version `0.0.1` in case there are only `UNCHANGED` classes or no classes. But indeed, your use case showed that in case there are no classes at all it should return `0.0.0` instead.

I have committed that change on the `master` branch. With `0.9.5-SNAPSHOT` your project worked on my machine.

**Comment by io7m** [comment]
Thanks for the quick response.

**Comment by siom79** [comment]
But there is still a problem if you have one class without any incompatible changes. In that case I would still suggest 0.0.1 as I would assume that you have changed anything (I mean compatible changes to the classes). Why would you build a new version without changing anything at all?

**Comment by io7m** [comment]
Yes, I'm going to start new projects at `0.0.1` from now on. I used to start at `0.1.0`. The semver spec says that before `1.0.0`, anything goes really, so I'll use whatever `japicmp` prefers.

**Comment by siom79** [comment]
In order to detect any changes I would have to check if the class files are binary equal. But even that would not be precise because a different compiler might create slightly different byte code for the same class and I would detect a change.

**Comment by io7m** [comment]
Yeah, I wouldn't put too much into this.

As I understand it, as soon as I publish a `0.0.1` release and move to `0.0.2`, everything should continue to work properly, right?

**Comment by siom79** [comment]
Yeah, the plugin will suggest 0.0.1 now if you have at least one class in your project assuming that you need to update the version anyhow. And according to semantic versioning you can only increment at least the last version number. But if you mind, you can also turn off semantic versioning checks by setting `<breakBuildBasedOnSemanticVersioning/>` to `false`.

**Comment by io7m** [comment]
OK, thanks!
