### ISSUE TITLE
Relax semantic versioning for < 1.0.0

### ISSUE THREAD

**Issue by io7m** [siom79/japicmp#165]
Hi.

Clause 4 of [semver](http://semver.org/) says:

>
> 4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Would it be possible to relax the rules for `japicmp` when project versions are less than `1.0.0`? Right now, I'm at version `0.0.2`. I've added a backwards-compatible change and `japicmp` wants me to jump to `0.1.0`. I'm pretty sure that if I make a backwards-incompatible change, it's going to request that I jump to `1.0.0`...

**Comment by io7m** [comment]
Er, by `japicmp`, I'm referring to the Maven plugin. And by _relax_, I mean _optionally relax_.

**Comment by siom79** [comment]
I think in your case the option `<breakBuildBasedOnSemanticVersioning>false</breakBuildBasedOnSemanticVersioning>' should work. The semver specification suggests to not apply the rules (e.g. by disabling the checks in japicmp) but it does not enforce this. So you can decide...

**Comment by io7m** [comment]
Hello!

The problem in my case is that `japicmp` is configured in an organization-wide parent POM that's used for some ~60 projects (and counting). To set a custom `<breakBuildBasedOnSemanticVersioning>` value would require redeclaring the plugin in each project that's at a version less than `1.0.0` and then remembering to re-enable it when the version hits `1.0.0`. This is something that's very easy to forget and the fact that it's disabled may go unnoticed. It would be a lot safer if the plugin could be persuaded to automatically start working when the version became `> 1.0.0`.

**Comment by io7m** [comment]
Had an idea: I might be able to achieve this using Maven profiles if I can get the profile to trigger based on the current project's version number. I'll let you know if it does/doesn't work...

**Comment by io7m** [comment]
Unfortunately, the ability to do this via profiles is currently sitting in limbo:

https://github.com/apache/maven/pull/80

I wonder if the most straightforward way to add this to the plugin would simply be to allow the plugin's execution to skip based on a given regex. Something like:

```
<runForVersionPattern>([1-9]+\.[0-9]+\.[0-9]+)(-[a-zA-Z0-9])?</runForVersionPattern>
```

The above pattern would be matched against the current project's version and the plugin would skip if the version did not match. By default, the version pattern would simply be `.*` but the pattern I gave above should run for versions greater than or equal to `1.0.0`, including snapshot versions, but should skip for versions less than `1.0.0`. This would avoid having to make any tricky changes to the logic for semantic versioning; it's just conditionally ignoring the rules.

**Comment by siom79** [comment]
Don't invest too much time on it. I have already started to implement it.
Today I won't have time to proceed. Maybe tomorrow...

io7m <notifications@github.com> schrieb am Sa., 11. März 2017, 14:09:

**Comment by io7m** [comment]
Ah, ok, thanks!

I'll wait and see.

**Comment by siom79** [comment]
I have committed a change set to the `master` branch. If you like, you can try it out:
```
git clone https://github.com/siom79/japicmp.git
cd japicmp
mvn install
```

**Comment by io7m** [comment]
Hi.

Thanks, I'll give this a go today!

**Comment by io7m** [comment]
Works! Thanks very much!
