### ISSUE TITLE
Any chance of a 0.10.0 release?

### ISSUE THREAD

**Issue by io7m** [siom79/japicmp#166]
'Ello!

Any chance you could push a 0.9.5 release so that we can use the new skipping and semantic versioning features?

**Comment by io7m** [comment]
I notice that the release will actually be `0.10.0` now. Is there any ETA for this? I could deploy my own version to my own `groupId`, but I'd rather use the official plugin.

**Comment by siom79** [comment]
I have just released 0.10.0. It should be available in Maven Central in a few hours.

**Comment by io7m** [comment]
Excellent. Thank you!
