### ISSUE TITLE
Should the addition of an unchecked "throws" be a source-incompatible change?

### ISSUE THREAD

**Issue by io7m** [siom79/japicmp#167]
Hi.

When an API permits an implementation to throw an unchecked exception such as `ArithmeticException`, I often put the exceptions in the interface method's `throws` clauses for the purposes of documentation. However, `japicmp` unexpectedly seems to consider the addition of an unchecked exception to a method to be a source-incompatible change.

See the following example project:

https://github.com/io7m/japicmp-bug-20170321

The generated report says:

![checked](https://cloud.githubusercontent.com/assets/612494/24162151/850ef9b8-0e5e-11e7-88e5-9f6144f040ad.png)

Is this intended behaviour?

**Comment by siom79** [comment]
Will be released with 0.10.0.

**Comment by io7m** [comment]
Nice work, thanks!
