### ISSUE TITLE
Overriding a method changes MINOR version?

### ISSUE THREAD

**Issue by tecywiz121** [siom79/japicmp#169]
This is more of a question about japicmp and semver than an issue.

## Setup
Let's say in version 1.0.0 you have a class:

```java
public class SuperBanana {
    public void doSomething() {}
}
```

And a subclass:

```java
public class SubBanana extends SuperBanana {}
```

Now you want to make a new version that overrides `doSomething()`:

```java
public class SubBanana extends SuperBanana {
    @Override
    public void doSomething() { /* ... */ }
}
```

## Question

Why does japicmp force a MINOR version change here?

Thanks!

**Comment by siom79** [comment]
The [semantic versioning specification](http://semver.org/) says:

> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. 

Further it elaborates:

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API.

As overriding a method in a subclass is not a bug fix, it must be a minor version change. According to section [13.4.24 of the Java Language Specification](https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html#jls-13.4.24) overriding a method does not break compatibility as already existing code will work on but may in polymorphic usage call the overriden method.

I know that you might argue now, what if orverriding the method fixes a bug? 😏  Well, as in this case the bug fix also changes the public API, I would still tend to say that this is rather a minor change than a patch.
