### ISSUE TITLE
Bad check for ignoreMissingOldVersion and ignoreMissingNewVersion

### ISSUE THREAD

**Issue by UnasZole** [siom79/japicmp#174]
Issue is found here : https://github.com/siom79/japicmp/blob/master/japicmp/src/main/java/japicmp/versioning/VersionChange.java#L25

If there is no old version and the plugin is configured to ignore missing old versions, then... the plugin throws an exception !
Shouldn't this check be prepended by a "not" operator, and same for the ignoreMissingNewVersion below ?

Concrete issue is that it breaks the build if 
breakBuildBasedOnSemanticVersioning = true
ignoreMissingOldVersion = true
and there is no existing version using semver.
Thus it prevents building the first artifact on a new repo, or the first semver artifact when you decide to implement semver on a repo which had different version patterns before.

**Comment by siom79** [comment]
Fix has been merged.

**Comment by UnasZole** [comment]
Thanks ! :-)
