### ISSUE TITLE
Exclusion of methods with default parameter

### ISSUE THREAD

**Issue by mlipkovich** [siom79/japicmp#176]
Hello,
we are facing the issue with Scala methods which contain parameters with default values. Please consider the following line
https://github.com/apache/flink/pull/4655/files#diff-85ce252587e0a07e8eb1ff8de4787608L515
The method `iterate` is annotated as PublicEvolving. This annotation is excluded in pom.xml file:
`<exclude>@org.apache.flink.annotation.PublicEvolving</exclude>`

As you can see from PR the method had a default parameter `keepPartitioning` which was removed in this PR. The compatibility check is failing with the following reason:
 ```
***! MODIFIED CLASS: PUBLIC org.apache.flink.streaming.api.scala.DataStream (not serializable)
---! REMOVED METHOD: PUBLIC boolean iterate$default$3()
+++ NEW METHOD: PUBLIC org.apache.flink.streaming.api.scala.DataStream setMaxParallelism(int)

            MODIFIED ANNOTATION: scala.reflect.ScalaSignature
```

It's complaining about removed method `iterate$default$3()`. The reason for it is that Scala creates methods for calculation of all default parameters 
http://docs.scala-lang.org/sips/completed/named-and-default-arguments.html
Method `iterate$default$3` means "method for calculation of the third default parameter". Annotation `PublicEvolving` is not applied for this method. I tried to exclude this method check using several ways

`<exclude>org.apache.flink.streaming.api.scala.DataStream#iterate$default$3[R](Boolean)</exclude>`						`<exclude>org.apache.flink.streaming.api.scala.DataStream#iterate$default$3(Boolean)</exclude>`
`<exclude>org.apache.flink.streaming.api.scala.DataStream#iterate$default$3[R]()</exclude>`
`<exclude>org.apache.flink.streaming.api.scala.DataStream#iterate$default$3()</exclude>`

but it didn't work

**Comment by siom79** [comment]
The filter uses a regular expression for matching. The squared brackets and the dollar sign are now escaped by japicmp.
