### ISSUE TITLE
It should be possible to build japicmp under jdk 1.9

### ISSUE THREAD

**Issue by siom79** [siom79/japicmp#182]
It should be possible to build japicmp under jdk 1.9. All maven plugins should be updated to the latest version that supports java 1.9 (see [here](https://cwiki.apache.org/confluence/display/MAVEN/Java+9+-+Jigsaw)).

**Comment by io7m** [comment]
Hello. I'm not sure this is completely fixed. Here's a recent Travis CI build on Oracle JDK9:

https://api.travis-ci.org/jobs/290399047/log.txt?deansi=true

Note that it's that same missing javax/xml/bind/JAXBException that I was previously only seeing when running the plugin on JDK 9...
