### ISSUE TITLE
Consistently use tabs or whitespace for indentation

### ISSUE THREAD

**Issue by gunnarmorling** [siom79/japicmp#185]
In generated reports (HTML) I'm seeing that tabs and whitespaces are used for indentation. It'd be nice to converge on one style, which will make the file easier to look at in editors such as vi.

There are also new lines with trailing whitespace in the generated HTML report; it'd be great of those could be removed, too, in order to avoid warnings when checking the generated file into git.

**Comment by twogee** [comment]
see #180

**Comment by gunnarmorling** [comment]
Cool, any idea when this PR will be merged?

**Comment by siom79** [comment]
Pull request has been merged.
