### ISSUE TITLE
Spurious stack trace when ignoreMissingNewVersion is true and no jar exists

### ISSUE THREAD

**Issue by sebbASF** [siom79/japicmp#195]
When ignoreMissingNewVersion is true and there is no new jar (e.g. mvn clean site), version 0.9.3 reports as follows:

[INFO] Generating "japicmp" report              --- japicmp-maven-plugin:0.9.3:cmp-report
[debug] No packaging support defined, no filtering
[debug] Searching for versions in versionRange: (,1.16-SNAPSHOT)
[debug] Parameter <oldVersionPattern> not configured, i.e. no version filtered.
[warn] No new version specified and file '/Path/target/classes' of artifact could not be opened as jar archive: /Path/target/classes (Is a directory)
[warn] Please provide at least one resolvable new version using one of the configuration elements <newVersion/> or <newVersions/>.
[warn] Skipping execution because no new version could be resolved/found.

This is as expected.

However version 0.9.4 (and later versions) show a stack trace:

[INFO] Generating "japicmp" report              --- japicmp-maven-plugin:0.9.4:cmp-report
[debug] No packaging support defined, no filtering
[debug] Searching for versions in versionRange: (,1.16-SNAPSHOT)
[debug] Parameter <oldVersionPattern> not configured, i.e. no version filtered.
[warn] No new version specified and file '/Path/target/classes' of artifact could not be opened as jar archive: /Path/target/classes (Is a directory)

java.io.FileNotFoundException: /Path/target/classes (Is a directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at japicmp.maven.JApiCmpMojo.populateArchivesListsFromParameters(JApiCmpMojo.java:314)
	at japicmp.maven.JApiCmpMojo.getOptions(JApiCmpMojo.java:651)
	at japicmp.maven.JApiCmpMojo.executeWithParameters(JApiCmpMojo.java:108)
	at japicmp.maven.JApiCmpReport.executeReport(JApiCmpReport.java:72)
...
[warn] Please provide at least one resolvable new version using one of the configuration elements <newVersion/> or <newVersions/>.
[warn] Skipping execution because no new version could be resolved/found.

The build still succeeds, but the stack trace is unnecessary and should ideally be suppressed.

**Comment by twogee** [comment]
Did you try [the latest version](https://mvnrepository.com/artifact/com.github.siom79.japicmp/japicmp/0.11.0)?

**Comment by sebbASF** [comment]
Yes, the issue occurs with 0.11.0.
That's what I meant by " (and later versions) ".
It first appears in 0.9.4

[INFO] Generating "japicmp" report              --- japicmp-maven-plugin:0.11.0:cmp-report
[debug] No packaging support defined, no filtering
[debug] Searching for versions in versionRange: (,1.16-SNAPSHOT)
[debug] Parameter <oldVersionPattern> not configured, i.e. no version filtered.
[warn] No new version specified and file '/Path/target/classes' of artifact could not be opened as jar archive: /Path/target/classes (Is a directory)

java.io.FileNotFoundException: /Path/target/classes (Is a directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at japicmp.maven.JApiCmpMojo.populateArchivesListsFromParameters(JApiCmpMojo.java:341)
	at japicmp.maven.JApiCmpMojo.getOptions(JApiCmpMojo.java:704)
	at japicmp.maven.JApiCmpMojo.executeWithParameters(JApiCmpMojo.java:136)
	at japicmp.maven.JApiCmpReport.executeReport(JApiCmpReport.java:71)

**Comment by twogee** [comment]
Sorry for being inattentive. Superficially, there's something with Maven API which says that the project has an artifact that is contained in a file (well, directory actually) '/Path/target/classes'. Could that be something that depends on Maven version? Please note that japicmp is developed against 3.0 which is pretty dated and uses a bunch of deprecated APIs (for 2.x compatibility, I presume).

**Comment by sebbASF** [comment]
No, it does not depend on the Maven version, it only depends on the japicmp version.
The only difference between the stack trace/no stack trace samples above is the japicmp version.

Please have a look at Issue #148 where ignoreMissingNewVersion was introduced.

It was designed to allow 'mvn site' to build without needing the jar and without failing the build.
That still works - the build succeeds - however the output includes an unnecessary stack trace.

The behaviour is OK. But the stack trace is unnecessary noise. That's all.

**Comment by twogee** [comment]
It looks like the stack trace comes from try with resources where an assumption is made that artifact files can only be JAR files. Is #196 good enough?

**Comment by sebbASF** [comment]
The proposed fix will suppress all logging for the case where an artifact is a directory. 
That may lose useful information. e.g. that it did indeed try the classes directory.

It might be better to wrap just the try block, and log a message to report that non-File artifact types cannot currently be handled. That will fix the example I gave.

The code will still produce a stack trace at line 345 if opening a file as a jar fails.
Is a stack trace needed here, so long as the exception message is logged?
I'm not 100% sure. It might be worth keeping the trace if ignoreMissingNewVersion is false.

**Comment by twogee** [comment]
Well, wrapping a try with a try would look like an overkill, wouldn't it? What confuses me is why catch (IOException) does not catch a subclass? Should there be an explicit catch (FileNotFoundException), then?

On the other hand, the code makes an explicit assumption that it expects artifact files, not directories. Therefore, if directories do appear, and that fact is of interest as well, then there must be some code checking for directories explicitly and informing the user about it without going through exception first.

**Comment by sebbASF** [comment]
I meant wrap the try block with the isFile() check:

if (file != null) {
  if (file.isFile() {
   try { ... }
  } else {
    log: Cannot handle file
  }
}

**Comment by twogee** [comment]
Well, isn't that the same as the current proposal?

**Comment by sebbASF** [comment]
Not quite.
The current proposal completely ignores artifacts that are not a file.
In my proposal they are logged.

I think it would be better to keep a log to show that the artifact has been seen.
The effect for the user is that they still see a log about /classes (or whatever) but there is no unnecessary stack trace.

**Comment by twogee** [comment]
I agree. No need to wrap another if around try, actually, just continue the loop.

**Comment by sebbASF** [comment]
I don't understand what you are proposing. Perhaps you could provide a new pull request?

**Comment by twogee** [comment]
Please have another look at the PR, it's updated.

**Comment by sebbASF** [comment]
I see.
That would work, however it would have to be recast if the code were to support class directories later. That's why I used an if/else wrapper.

I think the log message could be improved. Rather than showing:
"No new version specified and file '/abc/classes' of artifact is not a file at all."
why not simplify it to:
"No new version specified and artifact '/abc/classes' is not a file"

**Comment by twogee** [comment]
Thanks for reviewing. I adjusted the log message, yet I insist on keeping a separate if for readability.

**Comment by sebbASF** [comment]
I don't see the change to the log message.

**Comment by twogee** [comment]
Commit fae8fa8

**Comment by sebbASF** [comment]
The log message line is:

"No new version specified and file '" + file.getAbsolutePath() + "' of artifact is not a file."

which becomes:

"No new version specified and file '/abc/classes' of artifact is not a file at all."

I don't think this is clear enough.

**Comment by twogee** [comment]
The log message line should be
"No new version specified and file '/abc/classes' of artifact is not a file."
which is what you suggested, unless I misunderstood something.
Now when I thing of it, maybe "file attribute '/abc/classes' of artifact" would be less Margritte-esque 😃

**Comment by sebbASF** [comment]
That's not what I meant.

I think it should read something like the following when shown:

"No new version specified and artifact '/abc/classes' is not a file"

**Comment by twogee** [comment]
Picking a nit: the path is not a name of an artifact, just a place to find it.
Hope the new formulation of the log message works.

**Comment by sebbASF** [comment]
What new formulation? I don't see any changes.

Alternative suggestion:

"No new version specified and the artifact at '/abc/classes' is not a file"

**Comment by twogee** [comment]
Commit a00aed9.

**Comment by sebbASF** [comment]
That looks fine.

**Comment by twogee** [comment]
Thanks 😃

**Comment by chtompki** [comment]
I agree with @sebbASF on this one. I think that https://github.com/siom79/japicmp/commit/a00aed9982c4c6b45b087444baa7e3e8457d99e3 should fix the issue.

**Comment by garydgregory** [comment]
+1, please fix and release :-)

**Comment by siom79** [comment]
Pull request has been merged.
