### ISSUE TITLE
Building the jar for command line usage

### ISSUE THREAD

**Issue by trollwookiee** [siom79/japicmp#198]
Dummy question: 
I am only interested in using the CLI tool to generate my API diff reports, as a replacement for Jdiff.
Maven or And are not useful for me
What is the build procedure to get the japicmp.jar ?
Can't manage to find a how-to..

thanks

**Comment by siom79** [comment]
You can download japicmp directly from maven central:
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.github.siom79.japicmp%22%20AND%20v%3A%220.11.0%22.
Use the link labeled with jar-with-dependencies.jar.


Djamil Elaidi <notifications@github.com> schrieb am Mi., 21. Feb. 2018,
19:54:

**Comment by trollwookiee** [comment]
Thanks
