### ISSUE TITLE
Missing interface exception when only new class implements it

### ISSUE THREAD

**Issue by m-jarzebowski** [siom79/japicmp#200]
Hi,

when I try scan library with old and new classpath set I've got error message:

> Could not load 'x.y.z': x.y.z. Please make sure that all libraries have been added to the classpath (OLD CLASSPATH=:/Users/xyz/old/jars/*: / NEW CLASSPATH=:/Users/xyz/new/jars/*:) or try the option '--ignore-missing-classes'.

This happens when class from new jar implements interface that is not present in old classpath (only present in new claaspath) but old jar class equivalent dose not implement any interface at all.

japicmp.compat.CompatibilityChanges line 650 looks like this:
`interfaceClass = loadClass(implementedInterface.getFullyQualifiedName(), EnumSet.allOf(Classpath.class));`
but probably should be:
`interfaceClass = loadClass(implementedInterface.getFullyQualifiedName(), EnumSet.of(Classpath.NEW_CLASSPATH));`

Could you fix this?

Cheers,
MJ

**Comment by siom79** [comment]
I have tried to reproduce your case. The first jar only contains one class `MyClass` while the second jar contains this plus plus a new interface `MyInterface` which is implemented by the class. This is the output:
```
java -jar ../japicmp/japicmp/target/japicmp-0.11.1-SNAPSHOT-jar-with-dependencies.jar -o test-v1.jar -n test-v2.jar --old-classpath test-v1.jar --new-classpath test-v2.jar 
Comparing source compatibility of /home/mmois/Programmierung/test/test-v2.jar against /home/mmois/Programmierung/test/test-v1.jar
***  MODIFIED CLASS: PUBLIC japicmp.MyClass  (not serializable)
        ===  CLASS FILE FORMAT VERSION: 49.0 <- 49.0
        +++  NEW INTERFACE: japicmp.MyInterface
        ===  UNCHANGED CONSTRUCTOR: PUBLIC MyClass()
        ===  UNCHANGED METHOD: PUBLIC void foo()
+++  NEW INTERFACE: PUBLIC(+) ABSTRACT(+) japicmp.MyInterface  (not serializable)
        +++  CLASS FILE FORMAT VERSION: 49.0 <- n.a.
```
Can you provide more details about your case?

**Comment by m-jarzebowski** [comment]
Ok. I try to clarify. I've invoked command like this:
`java -jar japicmp-0.11.1-jar-with-dependencies.jar -n test-0.0.2.jar -o test-0.0.1.jar --new-classpath interfaces-0.0.2.jar --old-classpath interfaces-0.0.1.jar
E: Could not load 'org.example.interfaces.TestInterface': org.example.interfaces.TestInterface. Please make sure that all libraries have been added to the classpath (OLD CLASSPATH=:interfaces-0.0.1.jar: / NEW CLASSPATH=:interfaces-0.0.2.jar:) or try the option '--ignore-missing-classes'.`

test-0.0.1.jar contains org/example/test/App.class:
`public class App {
}`
test-0.0.2.jar contains org/example/test/App.class:
`public class App implements TestInterface {
}`
interfaces-0.0.1.jar is empty (BTW japicmp forces to provide both old-classpath and new-classpath even if one of the lib versions don't need additional classpath).
interfaces-0.0.2.jar contains org/example/interfaces/TestInterface.class:
`public interface TestInterface {
}`

**Comment by siom79** [comment]
Thank you very much for the detailed description. With its help I could reproduce the issue.

The last commit resolves the problem that japicmp reports `Could not load <class>` if both classpaths were specified separately and the class could not be loaded over the old classpath.
