### ISSUE TITLE
New methods in interfaces...

### ISSUE THREAD

**Issue by twogee** [siom79/japicmp#201]
... should count as incompatibility unless default implementation is provided (in Java 8+)

**Comment by siom79** [comment]
As of Chapter 13. of the [JLS](https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#jls-13.5.3):

> Adding a default method, or changing a method from abstract to default, does not break compatibility with pre-existing binaries, but may cause an IncompatibleClassChangeError if a pre-existing binary attempts to invoke the method.

Hence I decided to mark both changes (adding a new default method, changing a method from abstract to a default method) as incompatible, as both may be incompatible (depending on the inheritance hierarchy they are used in).

In general adding a method to an interface is only source incompatible but not binary incompatibly, as there is no existing code that does call the new method (see  [JLS](https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html#jls-13.5.3)).

**Comment by siom79** [comment]
This may be a general topic as there are may be other changes that may be incompatible in a specific situation but in another not.

Why do you want to mark a new default method as binary compatible?

**Comment by bdemers** [comment]
I want to extend an interface (and provide defaults).  I really just want some easy way of configuring the japicmp plugin to not fail the build in this scenario.

**Comment by hkalina** [comment]
I would welcome possibility to exclude this type of compatibility too.
If I understand correctly, pre-existing binary can invoke the new method (and cause IncompatibleClassChangeError) using reflection only.
(which is pretty uncommon and calling code should handle similar errors)

**Comment by siom79** [comment]
I have made it possible to configure whether certain changes are binary or source or even not incompatible at all (see #209).

**Comment by hkalina** [comment]
Great thanks. Unfortunately, if I am looking correctly, it does not allow to allow adding methods iff they have default implementation...

**Comment by siom79** [comment]
Take a look [here](http://siom79.github.io/japicmp/MavenPlugin.html). The table for the `overrideCompatibilityChangeParameters` parameter lists the following two checks for default methods:
* METHOD_NEW_DEFAULT
* METHOD_ABSTRACT_NOW_DEFAULT

You can set them both to binary and source compatible, if you like:
```
<overrideCompatibilityChangeParameters>
	<overrideCompatibilityChangeParameter>
		<compatibilityChange>METHOD_NEW_DEFAULT</compatibilityChange>
		<binaryCompatible>true</binaryCompatible>
		<sourceCompatible>true</sourceCompatible>
	</overrideCompatibilityChangeParameter>
	<overrideCompatibilityChangeParameter>
		<compatibilityChange>METHOD_ABSTRACT_NOW_DEFAULT</compatibilityChange>
		<binaryCompatible>true</binaryCompatible>
		<sourceCompatible>true</sourceCompatible>
	</overrideCompatibilityChangeParameter>
</overrideCompatibilityChangeParameters>
```

**Comment by siom79** [comment]
Then you must also configure `METHOD_ADDED_TO_INTERFACE` as binary and source compatible:
```
<overrideCompatibilityChangeParameters>
	<overrideCompatibilityChangeParameter>
		<compatibilityChange>METHOD_NEW_DEFAULT</compatibilityChange>
		<binaryCompatible>true</binaryCompatible>
		<sourceCompatible>true</sourceCompatible>
	</overrideCompatibilityChangeParameter>
	<overrideCompatibilityChangeParameter>
		<compatibilityChange>METHOD_ABSTRACT_NOW_DEFAULT</compatibilityChange>
		<binaryCompatible>true</binaryCompatible>
		<sourceCompatible>true</sourceCompatible>
	</overrideCompatibilityChangeParameter>
	<overrideCompatibilityChangeParameter>
		<compatibilityChange>METHOD_ADDED_TO_INTERFACE</compatibilityChange>
		<binaryCompatible>true</binaryCompatible>
		<sourceCompatible>true</sourceCompatible>
	</overrideCompatibilityChangeParameter>
</overrideCompatibilityChangeParameters>
```

**Comment by hkalina** [comment]
Yes, but that is something I would like to keep checked, as adding non-default method into interface is really breaking change.

**Comment by bdemers** [comment]
@hkalina Take a look at the groovy script support. It was pretty easy to add a single exclusion using the Maven plugin: 
https://github.com/okta/okta-sdk-java/blob/628416d/pom.xml#L286

And the actual groovy script:
https://github.com/okta/okta-sdk-java/blob/628416d/src/japicmp/postAnalysisScript.groovy#L27-L29

**Comment by siom79** [comment]
@hkalina You can also use the `<excludes/>` element as shown [here](http://siom79.github.io/japicmp/MavenPlugin.html).

**Comment by siom79** [comment]
@hkalina The last commit on this ticket changes the evaluation such that the two compatibility changes METHOD_NEW_DEFAULT and METHOD_ADDED_TO_INTERFACE are not set simultaneously.

**Comment by hkalina** [comment]
Amazing, works perfectly! :)

**Comment by garydgregory** [comment]
Can I add `overrideCompatibilityChangeParameter` for a specific class only?

**Comment by siom79** [comment]
@garydgregory No, currently you can change the settings only globally.
