### ISSUE TITLE
Feature Request: to be able to provide the exclusion list for the Maven plugin from an external file

### ISSUE THREAD

**Issue by rohanb1985** [siom79/japicmp#212]
Hello,
Please advise if it will be good feature to have the Exclusion list read from an external file. This will help to supply the list from outside the pom. Like when using Jenkins to build the pom, we can pass the file details from the Jenkins build parameters.

Thanks!

**Comment by siom79** [comment]
Do you only need the exclusion list or further configuration items to be
read from an external file?

PS: Why do you generate the pom by Jenkins but this generation cannot
create the exclusion list?

rohanb1985 <notifications@github.com> schrieb am Mo., 16. Juli 2018, 14:14:

**Comment by rohanb1985** [comment]
Hello,
I was trying to include this tool into our CI pipeline, and fail the build whenever there is a compatibility break. In case the break is accepted, the developer is supposed to update the file/method/field/... into the exclusion list, and re-trigger the build. 

Modifying the POM for each time is not a good idea. So, my request was to keep the most frequently modified attributes outside of the pom, in a separate file. This way the POM will remain constant. 

I tried the following way to pass the exclusion list from outside:
`mvn verify '-Dexcludes=com.rohan.digital.impl.common.DigitalAppListener,com.rohan.digital.impl.services.GetCustomerDetailsService#customerID'`

However, the above fails whenever the list contains some methods with comma separated parameters, like below - 
`mvn verify '-Dexcludes=com.rohan.digital.impl.common.DigitalAppListener,com.rohan.digital.impl.services.GetCustomerDetailsService#getCustomerDetails(String,String)'`

In the above case, the list is split based on the comma (as per maven default behavior), and the list becomes incorrect and throws an exception.

Hence the request to pass these details from outside.

thanks.

**Comment by twogee** [comment]
Or `.split(",(?![^()]*\\))")`

**Comment by rohanb1985** [comment]
@twogee - can you please elaborate a bit more? If you are referring to splitting of the list, it is the Maven's default behavior to split directly based on comma and store in a List. Can we modify this behavior? If yes, can you please advise me how? Thanks!

**Comment by twogee** [comment]
Sorry about a half-baked response. What makes you believe that Maven splits the property on comma? Could you please provide some logs?

**Comment by twogee** [comment]
Thanks, your description makes things clearer. Unless I'm mistaken, each exclude is split on [semicolon](https://github.com/siom79/japicmp/blob/0cac7d71a5531ebb1f3032958c35c67c848ad413/japicmp/src/main/java/japicmp/config/Options.java#L194), so maybe it's worth trying
```
<excludes><exclude>${exclusion.list}</exclude></excludes>
```
in the POM, where exclusion.list should be semicolon-separated.

**Comment by rohanb1985** [comment]
Thanks a lot!! This perfectly solves my requirement! I will mark this issue as closed.
Thanks again for your help!
