### ISSUE TITLE
Incompatibility Check for Synthetic Bridge Method

### ISSUE THREAD

**Issue by amitjoy** [siom79/japicmp#218]
Hi, we are working on comparing two JAR files for source and binary compatibility using the Java API of this library. One of the JARs has been compiled against an old build version of JDK 8 whereas the other JAR has been compiled against JDK 8 Build 171. In terms of source code, the JARs are exactly the same and never been touched.

The tool reports some binary incompatible changes in regard to synthetic bridge methods. We also checked the bytecodes of the class files using javap. But they look exactly the same (since they are never changed but compiled against old and new build version of Java 8 JDK).

Since the synthetic methods always play one of the important roles in binary compatibility, what could be the reason for such reporting by the library even though they are untouched (sourcecode-wise exactly the same)?

**Comment by amitjoy** [comment]
@xelaTech

**Comment by siom79** [comment]
Can you post the output of javap for both versions?

Thanks in advance.

Amit Kumar Mondal <notifications@github.com> schrieb am Mo., 30. Juli 2018,
16:31:

**Comment by siom79** [comment]
No reply since 30. Jul 2018. Please reopen if necessary.
