### ISSUE TITLE
Incompatibility when method is pulled up

### ISSUE THREAD

**Issue by rhierlmeier** [siom79/japicmp#222]
We have the following case:

* Version 0.0.1
```
public class A {
}
public class B extends A {
    public void foo();
}
public class C extends B {
}
```
* Version 0.0.2
```
public class A {
    public void foo();
}
public class B extends A {
}
public class C extends B {
}
```

japicmp reports a METHOD_REMOVED_IN_SUPERCLASS in class C. I think this is not correct. The method has been pulled up to class A. This should be compatible.

**Comment by rhierlmeier** [comment]
Issue is fixed in pull request #223

**Comment by jjlharrison** [comment]
I have just come up against this issue myself. I've tested against your pull request @rhierlmeier and it resolves the problem for me. Thank you.

**Comment by rhierlmeier** [comment]
I am glad, that my fix helped here. 
@siom79 Do we have any chance to get a release with this fix?

**Comment by siom79** [comment]
Release 0.13.1 is available.
