### ISSUE TITLE
Excluding methods from an included class by annotations

### ISSUE THREAD

**Issue by Bagge42** [siom79/japicmp#226]
I'm currently integrating japicmp into a build process using the Maven plugin. To do so I wanted to use annotations to mark what should be included in the compatibility check. The inclusion works fine, but when I attempted to include a class, but exclude one of the methods in that class it didn't seem to take. Japicmp still included the method that was marked with the exclude annotation.

I noticed you wrote a comment about it in December 2015: https://github.com/siom79/japicmp/issues/88#issuecomment-165054384
Here you mention it should be possible to exclude elements of the included class with another exclude annotation, but that it is to be tested. Did you get around to testing it? 

Either way it doesn't seem to be working for me, so I'd like to hear your input on the subject.

**Comment by siom79** [comment]
[Here](https://github.com/siom79/japicmp/blob/a349901dd57122c4a8e2d0b1b0bc7a16020efdd2/japicmp/src/test/java/japicmp/cmp/FilterTest.java#L580) is a test case that includes a class and excludes a method on it. From that I would conclude that it works.

Can you provide more details for your case?

**Comment by Bagge42** [comment]
Actually I can't, I tried to reproduce it now, but it seems to work for me. I must have done something wrong the other times, sorry for the inconvenience.
