### ISSUE TITLE
cmp goal of maven plugin breaks the build even though semver has been satisfied

### ISSUE THREAD

**Issue by elballa** [siom79/japicmp#231]
I changed the return type of a method of my API and compared my actual 1.7.4-SNAPSHOT project version with the latest project release 1.7.3. Cmp goal recognizes binary incompatibility and breaks the build as expected.
Changing current project version from 1.7.4-SNAPSHOT to 2.0.0-SNAPSHOT should solve the incompatibilty but cmp goal is still breaking the build.

**Comment by siom79** [comment]
@elballa : Please post your configuration.

**Comment by elballa** [comment]
<plugin>
    <groupId>com.github.siom79.japicmp</groupId>
    <artifactId>japicmp-maven-plugin</artifactId>
    <version>0.13.1</version>
    <configuration>
        <parameter>
            <htmlTitle>Backward compatibility report</htmlTitle>
            <reportOnlyFilename>true</reportOnlyFilename>
            <excludes>
                <exclude>*.internal.*</exclude>
            </excludes>
            <breakBuildOnBinaryIncompatibleModifications>true</breakBuildOnBinaryIncompatibleModifications>
            <breakBuildOnSourceIncompatibleModifications>true</breakBuildOnSourceIncompatibleModifications>
            <breakBuildBasedOnSemanticVersioning>true</breakBuildBasedOnSemanticVersioning>
            <onlyModified>true</onlyModified>
        </parameter>
    </configuration>
    <executions>
        <execution>
            <phase>verify</phase>
            <goals>
                <goal>cmp</goal>
            </goals>
        </execution>
    </executions>
</plugin>

**Comment by siom79** [comment]
@elballa: Please set `breakBuildOnBinaryIncompatibleModifications` and `breakBuildOnSourceIncompatibleModifications` to `false`, because they are stronger than `breakBuildBasedOnSemanticVersioning`.
