### ISSUE TITLE
fails build: <reportSet>'s <path> on Windows generates invalid report output filename

### ISSUE THREAD

**Issue by jeffjensen** [siom79/japicmp#235]
Using 0.14.0, this config on Windows:
>     <file>
>       <path>${project.build.directory}/${project.artifactId}-${project.version}.${project.packaging}</path>
>     </file>

Results in this output file path and name which is in error with the drive letters and pathing:
>D:\\(path)\\target\\site\\(group)\_(artifact)\_(oldVersion)D:\\(path)\\target\\(artifact)-(newVersion).(packaging)_output.html

**Comment by siom79** [comment]
Fixed with #236.
