### ISSUE TITLE
Improve the default <reportSet> output anchor text, add config option

### ISSUE THREAD

**Issue by jeffjensen** [siom79/japicmp#236]
Using 0.14.0, the generated anchor text for report links is 
>(group)\_(artifact)\_(oldVersion)(group)\_(artifact)\_(newVersion)

This becomes quite long (doesn't fit well in the page) and not attractive.  

One idea for default text is the <reportSet>'s <id> field as that's manually specified.

Would like a "linkText" config option to manually specify.

**Comment by siom79** [comment]
Released with 0.14.1.
