### ISSUE TITLE
[maven plugin] Expose parameters as user properties

### ISSUE THREAD

**Issue by kingle** [siom79/japicmp#240]
It would be nice to be able to set all the various parameter configuration values in the `properties` section of our maven pom.xml as an alternative to having to add them under the plugin configuration.  This would allow better flexibility for use in a parent pom, so child projects could easily flex configuration without having to override in plugin section.  It would also allow easy way to perform the more fine-grained skips via commandline (`mvn clean package -Djapicmp.skipXmlReport`)

I believe all that would be needed would be to add the appropriate `property` in the annotations for all the properties currently under Parameter
 https://github.com/siom79/japicmp/blob/23d1827c725e605807721db54d665c3b69cde816/japicmp-maven-plugin/src/main/java/japicmp/maven/Parameter.java#L5

**Comment by siom79** [comment]
Released with 0.14.2.
