### ISSUE TITLE
Add METHOD_ADDED_TO_PUBLIC_CLASS check

### ISSUE THREAD

**Issue by kingle** [siom79/japicmp#241]
For semantic version checks, many of us take the stance that if a public method is added to a public class, most likely it is introducing new functionality and the version should be a MINOR bump.  It would be nice to have the ability to allow a configuration to enforce a MINOR version bump if we have configured `breakBuildBasedOnSemanticVersioning` and a new public method is added (on a public class).

**Comment by siom79** [comment]
Did you try ``overrideCompatibilityChangeParameter``?

**Comment by kingle** [comment]
That's what I'm trying to do, but I do not see the appropriate check available to override.

**Comment by siom79** [comment]
You are right. I have to add it.

**Comment by dannil** [comment]
Any update on this? Would be a great feature to have as I'm experiencing the same issue.

**Comment by siom79** [comment]
Released with 0.14.3.
