### ISSUE TITLE
Allow comparison with Maven SNAPSHOTs

### ISSUE THREAD

**Issue by jjlharrison** [siom79/japicmp#250]
I have a project where we often start work on a new minor version before the previous major version is released. For example, the development team has started work on 24.1.0 before 24.0.0 has been released (it's currently undergoing testing).

To allow JAPICMP to enforce semantic compatibility, I would like it to consider the latest 24.0.0 SNAPSHOT. I have managed to get it working locally by removing the call to the `filterSnapshots` method.

Is this a use case that the plugin should cater for or should I just fork for my purposes?

**Comment by siom79** [comment]
Is it possible to implement a configuration option to allow both cases? In
that case you are free to create a PR.

James Harrison <notifications@github.com> schrieb am Mi., 9. Okt. 2019,
16:03:
