### ISSUE TITLE
Allow postAnalysisScript from maven plugin to be loaded from classpath

### ISSUE THREAD

**Issue by juanpablo-santos** [siom79/japicmp#257]
`postAnalysisScript` parameter always loads the script [from an existing file](https://github.com/siom79/japicmp/blob/master/japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java#L206) on the project. It would be nice if it could be readed too from classpath, so it could be included and readed from inside a provided plugin dependency, hence not having to copy the analysis script over every project using the plugin.

thx!

**Comment by reckart** [comment]
Just was about to open the same issue ;)

**Comment by maxime-michel** [comment]
This can probably be closed since this month's release, can't it? It's misleading.

**Comment by juanpablo-santos** [comment]
indeed, this issue seems tackled in #274, hence closing.
