### ISSUE TITLE
skip plugin execution parameter does not work

### ISSUE THREAD

**Issue by arvindkrishnakumar-okta** [siom79/japicmp#262]
Read the doc at https://siom79.github.io/japicmp/MavenPlugin.html and tried to use the `skip` parameter in the plugin configuration. 

`<plugin>
         <groupId>com.github.siom79.japicmp</groupId>
                    <artifactId>japicmp-maven-plugin</artifactId>
                    <version>0.14.3</version>
                    <configuration>
                        <parameter>
                            <skip>true</skip>
                            <onlyModified>true</onlyModified>
                        </parameter>
                    </configuration>`

maven throws the below error:

`[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.14.3:cmp (japicmp) on project okta-sdk-api: Unable to parse configuration of mojo com.github.siom79.japicmp:japicmp-maven-plugin:0.14.3:cmp for parameter skip: Cannot find 'skip' in class japicmp.maven.Parameter -> [Help 1]`

maven version used: `Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)`. 

According to the docs, this param should work from Maven 3.0.3 onwards?

**Comment by siom79** [comment]
Yes, the parameter should work. But it is now located inside the ``<configration>`` block and no longer inside the ``<parameter>`` block.
