### ISSUE TITLE
Removal of checked exception from method signature is not detected

### ISSUE THREAD

**Issue by Snipx** [siom79/japicmp#263]
There is currently `METHOD_NOW_THROWS_CHECKED_EXCEPTION` inspection for addition of checked exceptions into method signature.
However, there does not seem to be an inspection for checked exception removal from method signature.
Imagine the following case:
```
    public void throwingMethod() throws IOException {

    }

    public void clientMethod() {
        try {
            throwingMethod();
        } catch (IOException exc) {
        }
    }
```

If `throws IOException` is removed, `clientMethod` will not compile anymore, so it's definitely at least source compatibility violation. I am not sure about binary compatibility here.

I might be missing something, but I expect such change to be detected as a breaking change by the plugin and it's currently not detected to the best of my understanding.
Thanks in advance

**Comment by siom79** [comment]
Fixed with 0.14.4
