### ISSUE TITLE
Starting with 0.15.0 maven plugin fails if previous version of an artifact can't be resolved

### ISSUE THREAD

**Issue by juanpablo-santos** [siom79/japicmp#283]
With [0.14.4](https://github.com/siom79/japicmp/blob/japicmp-base-0.14.4/japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java#L279-L281), missing artifacts don't break the build, whereas with [0.15.0](https://github.com/siom79/japicmp/blob/japicmp-base-0.15.2/japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java#L273-L275), they do. This change of behaviour isn't mentioned on the [release notes](https://github.com/siom79/japicmp/blob/japicmp-base-0.15.2/src/site/markdown/ReleaseNotes.md) and the `ignoreNonResolvableArtifacts` parameter doesn't seem to be taken into account, so maybe this change wasn't intentional?

**Comment by arturobernalg** [comment]
H @juanpablo-santos  @siom79 

Yep, the new version (0.15.0) breaks the builds  when unable to find or does not exist the binary. it seem is ignoring the ignoreNonResolvableArtifacts param

`: Versions of archives indicate a minor change but binary incompatible changes found.`

**Comment by siom79** [comment]
Fixed: 0.15.3
