### ISSUE TITLE
No compatibility change is detected for removed public method

### ISSUE THREAD

**Issue by gszadovszky** [siom79/japicmp#286]
[This change](https://github.com/apache/parquet-mr/commit/48f5195cfb2662f021e928211687192249752818#diff-fdb3f98a77cd841492f0076888ed6c94dd5aea0a8945d37377ccfab33a38994f) in parquet-mr updated the signature of a public method (in other words it removed the old method and added a new one). It is clearly a break change. Meanwhile, japicmp maven plugin did not fail our build. By checking the report the removed method got into it with red but there is "n.a." in the compatibility changes column.
Please fix this issue and/or provide a workaround so we would detect such breaking changes in time.

**Comment by siom79** [comment]
Did you check the inheritance hierarchy? Is the "new" method just an overridden method from a superclass?

**Comment by gszadovszky** [comment]
My bad, you are right. Both methods (the removed and the new one) are overridden from the parent. So syntactically it is not a breaking change. (In the current case semantically it is a breaking change but it is not something a compatibility checker can identify.)

Thanks for checking!
