### ISSUE TITLE
Markdown report

### ISSUE THREAD

**Issue by scordio** [siom79/japicmp#291]
I would like to use `japicmp` to provide automated feedback to pull requests about binary compatibility.

Currently, I plan to add a comment to pull requests using the diff-like output.
However, I like more the HTML visual impact so I tried some tools to have an automated conversion from HTML to Markdown, but the result is not that great. Also, embedding the HTML report directly in a comment does not work due to unsupported tags.

Would you be willing to add a Markdown report with layout and content similar to the HTML one?

If you like the idea, I can try to raise a PR about it.

**Comment by siom79** [comment]
Have you seen the groovy plugin support [here](https://siom79.github.io/japicmp/MavenPlugin.html)? You can write a groovy script that creates a Markdown report.

On the other hand, I would merge a Markdown report if you want to implement that.

**Comment by scordio** [comment]
Thanks, I didn't think about using the groovy support for that purpose. I think the effort for the script might be comparable to a native implementation, so I'll probably raise a PR for it.

Is it ok to rely on an [existing library for Markdown generation](https://github.com/Steppschuh/Java-Markdown-Generator), bringing that in as a new dependency?

**Comment by siom79** [comment]
OK. Then go for it.

It is ok to include a 3rd party library for that.

Stefano Cordio ***@***.***> schrieb am Mo., 12. Juli 2021,
15:41:

**Comment by scordio** [comment]
I started looking into the necessary changes. Would you suggest adding the Markdown generation to `XmlOutputGenerator` (which is currently taking care of both the XML and the HTML reports), or would it be better to create a new `MarkdownOutputGenerator`?

I tend to favor the former as the Markdown structure would mimic the HTML one, but I'm not sure that `XmlOutputGenerator` would still be a good name for that class.

**Comment by siom79** [comment]
I would prefer to have a new one, just like the StdoutOutputGenerator.

Am Do., 12. Aug. 2021 um 13:30 Uhr schrieb Stefano Cordio <
***@***.***>:

**Comment by scordio** [comment]
Although I'm still behind with this one (almost one year later 😄), this is also a good fit with the new [job summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) feature of GitHub actions.

**Comment by scordio** [comment]
Superseded by #404 / #405.
