### ISSUE TITLE
Behaviour of optional.or

### ISSUE THREAD

**Issue by cdietrich** [siom79/japicmp#297]
why does

```japicmp.util.Optional.Absent.or(Optional<? extends T> secondChoice)``` return this and not `secondChoice`?
compared with guavas

```
  public Optional<T> or(Optional<? extends T> secondChoice) {
    return (Optional<T>) checkNotNull(secondChoice);
  }
```

and javas?

**Comment by siom79** [comment]
You are right. It should not return this but secondChoice. ;)
