### ISSUE TITLE
Incorrectly reports method changes

### ISSUE THREAD

**Issue by oliverburn** [siom79/japicmp#31]
I have been testing the `0.2.3` version and have noticed that it does not correctly report changes to methods. I have created a [repository](https://bitbucket.org/ojburn/japicmp-bugs/overview) for demonstrating the problems I am seeing. To reproduce:

    git clone https://ojburn@bitbucket.org/ojburn/japicmp-bugs.git
    cd japicmp-bugs/method-changes
    ./gradlew jar cmp

The first problem is changing the method `compareTo` from:

    public class MethodAnnotations implements Comparable<String>
    {
        @Override
        public int compareTo(String o)
        {
            return 0;
        }
    }

to:

    public class MethodAnnotations
    {
        public int compareTo(String o)
        {
            return 0;
        }
    }

japicmp reports that the method is both `UNCHANGED` and `REMOVED`

    Processing samples.MethodAnnotations, change status MODIFIED
        Number methods: 2
            method compareTo, change status UNCHANGED, compat true
            method compareTo, change status REMOVED, compat false

The second problem is that when a method return type is changed, `japicmp` is reporting that a method had been `REMOVED` as well as a `NEW` one added. I would suggest that japicmp should report that the method has been `CHANGED`. 

An example would be the changes in the return types from:

    public interface InterfaceMethodChanges
    {
        void returnChangedVoidToInt();
        int returnChangedIntToVoid();
        String returnChangedStringToObject();
    }

to:

    public interface InterfaceMethodChanges
    {
        int returnChangedVoidToInt();
        void returnChangedIntToVoid();
        Object returnChangedStringToObject();
    }

**Comment by siom79** [comment]
Thank you for reporting these two issues.

You may be astonished, but if you take a closer look at the two class files, you will see that there are really two methods for the first class and that there is only one method for the second version of the class ([javap](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javap.html) is a disassembler that comes with the JDK):

```
>javap Interfaces$InterfaceComparableRemoved.class
Compiled from "Interfaces.java"
public class japicmp.test.Interfaces$InterfaceComparableRemoved implements java.lang.Comparable<java.lang.String> {
  final japicmp.test.Interfaces this$0;
  public japicmp.test.Interfaces$InterfaceComparableRemoved(japicmp.test.Interfaces);
  public int compareTo(java.lang.String);
  public int compareTo(java.lang.Object);
}

>javap ..\..\japicmp-test-v2\target\Interfaces$InterfaceComparableR
emoved.class
Compiled from "Interfaces.java"
public class japicmp.test.Interfaces$InterfaceComparableRemoved {
  final japicmp.test.Interfaces this$0;
  public japicmp.test.Interfaces$InterfaceComparableRemoved(japicmp.test.Interfaces);
  public int compareTo(java.lang.String);
}

```
This has something to do with the fact that in Java Generics are not part of the class file ([Type Erasure](http://docs.oracle.com/javase/tutorial/java/generics/erasure.html)). Or to be more precise this is the case of a [bridge method](http://docs.oracle.com/javase/tutorial/java/generics/bridgeMethods.html).

Currently I am using [Method Descriptors](http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.3.3) to distinguish different methods within a class. The fact that you can overload a method makes it in theory in some situations impossible to detect whether two methods with the same name and different parameters have changed or have been added/removed. Hence I follow the default diff principle, that I show the changed method as removed and added. But I think it should be possible to leave the return value out of the computation and report such cases as a change.
I will see what I can do...:smirk:

**Comment by siom79** [comment]
* Return types are reported as modifications instead of addition/removal since version 0.3.0
* New [issue](https://github.com/siom79/japicmp/issues/41) for the detection of bridge methods has been created
