### ISSUE TITLE
Constructor `protected` -> `private` in `final` class detected as `CONSTRUCTOR_LESS_ACCESSIBLE`

### ISSUE THREAD

**Issue by scordio** [siom79/japicmp#310]
In a `final` class, a visibility change of a constructor from `protected` to `private` is detected as `CONSTRUCTOR_LESS_ACCESSIBLE`:

```
Comparing binary compatibility of assertj-core-3.22.1-SNAPSHOT.jar against assertj-core-3.22.0.jar
***! MODIFIED CLASS: PUBLIC FINAL org.assertj.core.api.Fail  (not serializable)
	===  CLASS FILE FORMAT VERSION: 52.0 <- 52.0
	***! MODIFIED CONSTRUCTOR: PRIVATE (<- PROTECTED) Fail()
```

![Screenshot 2022-01-14 at 15 07 06](https://user-images.githubusercontent.com/26772046/149528255-7212386e-4277-418e-aa38-201b3449ed20.png)

Although it's a proper detection considering only the constructor visibility, I am wondering if this could be correlated with the fact that the class is `final` and there is no way it can be extended, so it shouldn't be an incompatible change.

**Comment by siom79** [comment]
Fixed: 0.15.5
