### ISSUE TITLE
Overriding default methods in interfaces reported as binary incompatible.

### ISSUE THREAD

**Issue by pivotal-jbarrett** [siom79/japicmp#312]
I am confused as to why overriding the methods from one interface in another between releases is detected as a binary incompatible change.

I am trying to deprecate methods inherited by poor choices in inheritance so that we avoid implementations using those methods and can later drop the bad inheritance.

Effectively we are going from this:
```java
interface Something extends SomethingElse {
    default void doSomething() {}
}

interface SomethingElse {
    default void doSomethingElse() {}
}
```
to:
```java
interface Something extends SomethingElse {
    default void doSomething() {}
    @Deprecated
    @Override
    default void doSomethingElse() {}
    default void doSomethingBetter() { doSomethingElse(); }
}

interface SomethingElse {
    default void doSomethingElse() {}
}
```

It is reported as:
Error | Class Something: Is not binary compatible
-- | --
Error | Method Something.close(): Is not binary compatible<BR>METHOD_NEW_DEFAULT
Error | Method Something.doSomethingBetter(): Is not binary compatible<br>METHOD_NEW_DEFAULT
Error | Method Something.doSomethingElse(): Is not binary compatible<br>METHOD_NEW_DEFAULT<br>ANNOTATION_DEPRECATED_ADDED

I would appreciate any insight into this issue and how best to deal with it.

**Comment by siom79** [comment]
What version do you use? In the current version 0.15.4 I cannot reproduce this issue.
