### ISSUE TITLE
Show short usage

### ISSUE THREAD

**Issue by eldur** [siom79/japicmp#32]
As terminal user without a 64" display with 180 lines in my terminal session, I want to read an error message without scrolling :wink: 

compare to other shell tools like ```find``` -> ```find --unknown-opt```, ```find --help```, ```man find```

* If I enter ```.. -jar japicmp.jar``` I only want to see short usage information and an error message or the successful result of japicmp
* exit codes should be zero on success and according to other shell tools *1* or *2* ... up to 255 
* If I enter ```.. -jar japicmp.jar --help``` I want to see the full help - man page equivalent and **no** error message, the exit code sould be *zero*

actual on feature-semver branch
```
$  .. -jar japicmp.jar --help
E: Required option '-o' is missing
NAME
        java -jar japicmp.jar - Compares jars
...
...
$ echo $?
255
$ # why is -o required for help output?
```

I tought it was fixed with 145b7f6f31fa9e67fc876e55280a548deca0c4d7 and 3ab5e55de3d5036dccc52549f6774b710eb2f9e8 but I can't find its content anymore. ... Maybe also abandoned with my other changes ... It feels a little bit like "Don't write test and don't send me pull requests, I'll rollback them later" :wink:  :smile: 

See also: http://tldp.org/LDP/abs/html/exitcodes.html

**Comment by eldur** [comment]
I've fixed this again with a revert in pull #30

**Comment by siom79** [comment]
First of all I have to say, that I was a little bit surprised to see changes in CLI code in the pull request for the semver-feature. But I pulled it in and found out that now we get a stacktrace in case of an invalid archive name:

```
>java -jar japicmp-0.2.3-jar-with-dependencies.jar -n abc.jar
Execution of JApiCmp failed: japicmp.exception.JApiCmpException: File 'D:\Programmierung\japicmp\releases\abc.jar' does not exist.
java.lang.IllegalStateException: japicmp.exception.JApiCmpException: File 'D:\Programmierung\japicmp\releases\abc.jar' does not exist.
        at japicmp.cli.JApiCli$Compare.create(JApiCli.java:105)
        at japicmp.cli.JApiCli$Compare.run(JApiCli.java:52)
        at japicmp.JApiCmp.run(JApiCmp.java:34)
        at japicmp.JApiCmp.main(JApiCmp.java:12)
Caused by: japicmp.exception.JApiCmpException: File 'D:\Programmierung\japicmp\releases\abc.jar' does not exist.
        at japicmp.exception.JApiCmpException.of(JApiCmpException.java:31)
        at japicmp.cli.JApiCli$Compare.verifyExisting(JApiCli.java:155)
        at japicmp.cli.JApiCli$Compare.validFile(JApiCli.java:112)
        at japicmp.cli.JApiCli$Compare.create(JApiCli.java:93)
        ... 3 more
```
This is something I did not wanted to have. When the user provides an invalid option or argument for an option, we should present him/her a meaningful error message and no stacktraces.

Then I found out that the methods `verifyExisting()` and `verifyJarArchive()` have gone.

This may have happened accidentally, but it made clear, that pull requests should only cover one aspect to concentrate on and not mix different things together. 

A second thing that bothered me, was the class `ShortHelpOption`. This looks like something that should be added to the airlift library itself. We should not start to implement such things in the scope of your library, as we now depend heavily on their implementation (and we have to change it when they change something).

Please do not understand me wrong, your help is appreciated. But please open a new ticket and send separate pull requests for different features. And be aware that I do not want to pull in heavy dependencies on other libraries (except the one on google's guava :smirk:).

**Comment by eldur** [comment]
* Okay the exception was not my intention :wink: 
* I'll check the disposition of ```verify*``` methods
* I'm also a big fan of pull requests by feature but I don't know your preferred  workflow (usage of develop and master was unclear) -- give me a try
* full ack with a reduced dependency set, do you prefer to rewrite CLI parsing, or is there an easier way to this?

**Comment by siom79** [comment]
No problem. Meanwhile I have recreated on the `feature-semver` branch a state that fixes the problems above, although I did not integrate the short usage. 

Regarding the workflow I would suggest to use the [gitflow](http://nvie.com/posts/a-successful-git-branching-model/). I started it (master, developement and feature-semver) but also did not use it completely. :smirk:

Regarding CLI parsing I would like to stick with the current airline solution. Your point about the error message is correct. Hence we should not present the full help to the user, just a message telling him to invoke the program with `--help` to get more information. Therefore I favor this solution:
```
E: Required option -n is missing.
See '--help' or '-h' for more information.
```
This is similar to the invocation of git with an invalid option:
```
See 'git --help'.
```

**Comment by eldur** [comment]
(have you ever worked gitflow?)

**Comment by siom79** [comment]
I have tried to follow the basic principle up to now. :smile:

**Comment by siom79** [comment]
By the way, from my point of view the current state of the `develop` branch is ready for release. Do you  have any valid objection against a release?

Do you want to be mentioned as contributor? If so, please send me a pull request with a contributor element in the pom.xml that mentions you as a contributor.

**Comment by eldur** [comment]
it think this issue is done and can be closed
