### ISSUE TITLE
japicmp programmatically exclude package for external dependencies

### ISSUE THREAD

**Issue by chaudharydeepak** [siom79/japicmp#325]
I am using japicmp library to compare different versions of spring boot applications. 

`
JarArchiveComparatorOptions comparatorOptions = new JarArchiveComparatorOptions();
        comparatorOptions.getFilters().getExcludes().add(new JavadocLikePackageFilter("org.springframework.*", true));
`
My understanding was to exclude any packages that we don't want to compare as above - instead, the application fails with following exception:
`
Exception in thread "main" japicmp.exception.JApiCmpException: Could not load 'org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler'
`

any hints how to exclude such standard dependencies from being compared? Thank you for your help.

**Comment by chaudharydeepak** [comment]
I looked at some other code bases on github and i understood how to use the api. just curious, is there any documentation of the api / libraries? Thank you for all your help.

**Comment by siom79** [comment]
There is documentation regarding the maven plugin and the ant plugin [here](https://siom79.github.io/japicmp/). The raw API is seldomly used; hence, there is not much documentation.
