### ISSUE TITLE
HTML output improvements

### ISSUE THREAD

**Issue by TheLQ** [siom79/japicmp#33]
In my HTML output I noticed any class with changes has an additional "Superclass UNCHANGED" table, even with the -m option passed. This takes up a lot of space in large diffs and is just noise. Ignoring the -m option seems like a bug. 

Wishlist improvements:
 - Support maven site reports - This would be a nice feature for those of us that still generate full maven sites for reports like this. The only issue is CSS which might be better in separate file anyway so people can use their own CSS. 
 - Hide Superclass when its a new class - Pointing out that a new class extends Object doesn't really seem useful. The only debatable useful instance is when extending anything else, but it just seems like noise since you'll still need Javadoc or IDE's to find out what org.random.project.SomeClass actually does. 
 - Add generation date - Since the full path of the jars is already at the top, adding a "generated date" line could be useful for tracking snapshots and versions since the compared jars aren't always static. 

Thanks for finishing the HTML reports though, its still pretty useful!

**Comment by siom79** [comment]
With release 0.5.1 the maven plugin supports site reports.
