### ISSUE TITLE
Class had changed, but the result is UNCHANGED.

### ISSUE THREAD

**Issue by javalover123** [siom79/japicmp#336]
cn.hutool.bloomfilter.bitMap.IntMap.remove() had changed, but the result is UNCHANGED.

java -jar japicmp-0.16.0-jar-with-dependencies.jar --ignore-missing-classes -n hutool-all-4.5.15.jar -o hutool-all-4.5.10.jar
[New jar](https://search.maven.org/artifact/cn.hutool/hutool-all/4.5.15/jar)
[Old jar](https://search.maven.org/artifact/cn.hutool/hutool-all/4.5.10/jar)

![image](https://user-images.githubusercontent.com/9191388/189334862-9a35c3ec-261c-4f3e-8a44-bedd13ddb810.png)

**Comment by siom79** [comment]
What has changed?

**Comment by javalover123** [comment]
New version delete static field MAX, and modify remove().

[Old](https://github.com/dromara/hutool/blob/f652ef60ca546fa5050da35288ee53a62f14cf2f/hutool-bloomFilter/src/main/java/cn/hutool/bloomfilter/bitMap/IntMap.java#L51)
[New](https://github.com/dromara/hutool/blob/ccd6f4bec53919b65baeaaa3d433b474c43a0282/hutool-bloomFilter/src/main/java/cn/hutool/bloomfilter/bitMap/IntMap.java#L50)

**Comment by siom79** [comment]
The signature of the remove method did not change: void remove(long). The MAX constant is private.
