### ISSUE TITLE
Exclude unchanged classes and methods from HTML report

### ISSUE THREAD

**Issue by NotMyFault** [siom79/japicmp#355]
Hey,

I'm using the `--html-file` file option to generate an HTML report. Would it be possible to skip unchanged classes?
I'm looking for a way to generate a report that covers changed contents only, I don't need to document everything that didn't change.
The `-m` option reports a few unchanged classes still.

Thanks in advance!

**Comment by siom79** [comment]
Have you tried `onlyBinaryIncompatible` and `onlyModified` (see [here](https://siom79.github.io/japicmp/MavenPlugin.html))?

**Comment by kayhong** [comment]
I tried command 
`java -jar japicmp-0.17.3-SNAPSHOT-jar-with-dependencies.jar -n /home/dc-user/software/jdk8u362-b09/jre/lib/rt.jar -o /home/dc-user/software/zulu8.72.0.17-ca-jdk8.0.382-l_x64/jre/lib/rt.jar --html-file /home/dc-user/software/report.html`

it runs forever. if I remove html option, it will output directly.


anything I'm wrong to generate html report?

**Comment by siom79** [comment]
@kayhong:
I guess you need to increase heap space for the java process. If there is not much memory available, the jvm needs to do a lot of garbage collection that costs time.
On my machine I have run it that way:
```
java -Xms4g -Xmx4g -jar target/japicmp-0.17.2-SNAPSHOT-jar-with-dependencies.jar -o /opt/java/jdk1.8.0_321/jre/lib/rt.jar -n /opt/java/jdk1.8.0_321/jre/lib/rt.jar --ignore-missing-classes --html-file report.html
```

**Comment by NotMyFault** [comment]
> Have you tried `onlyBinaryIncompatible` and `onlyModified` (see [here](https://siom79.github.io/japicmp/MavenPlugin.html))?

That was it, thanks!
