### ISSUE TITLE
htmlTitle not actually added to html file

### ISSUE THREAD

**Issue by bradleylarrick** [siom79/japicmp#362]
I found that when generating the japicmp report during the site phase of a maven build, the specified htmlTitle value was not actually added to the resulting html file. As a result the browser tab and breadcrumb only contained the project name. I resolved the issues by adding the following code the executeReport() in JApiCmpReport.java:

```
Sink sink = getSink();
sink.head();
String title = pluginParameters.getParameterParam().getHtmlTitle();
if (title != null) {
	sink.title();
	sink.text(title);
	sink.title_();
}
sink.head_();
sink.rawText(htmlString);
sink.close();
```

**Comment by siom79** [comment]
Fixed. Will be part of the next release.

**Comment by bradleylarrick** [comment]
Confirmed. Thanks for the quick response!
