### ISSUE TITLE
Regression CLASS_GENERIC_TEMPLATE_CHANGED

### ISSUE THREAD

**Issue by velo** [siom79/japicmp#368]
Hi,

I might have found a regression.

On japicmp 0.16.0 (tested 0.15.3 too, and workds) my project builds fine as expected.
On japicmp 0.17.1 it fails `There is at least one incompatibility: com.querydsl.mongodb.MongodbExpressions.all(com.querydsl.core.types.dsl.ListPath,java.util.Collection):CLASS_GENERIC_TEMPLATE_CHANGED`
Also tested with all 0.17.x and 0.18.x releases.

On my side, this is a new static method AND is a new major release 6.0-SNAPSHOT.

https://app.circleci.com/pipelines/github/OpenFeign/querydsl/508/workflows/a08cc0c7-2acd-437c-a34a-6001e4358571/jobs/3172

[japicmp.xsd.txt](https://github.com/siom79/japicmp/files/13360971/japicmp.xsd.txt)
[japicmp.diff.txt](https://github.com/siom79/japicmp/files/13360972/japicmp.diff.txt)
[japicmp.html.txt](https://github.com/siom79/japicmp/files/13360973/japicmp.html.txt)
[japicmp.xml.txt](https://github.com/siom79/japicmp/files/13360974/japicmp.xml.txt)

**Comment by amousavigourabi** [comment]
Hi, we are also facing similar behaviour on wholly new methods over at Apache Parquet after updating japicmp from 0.16.0 to 0.18.1 and later 0.18.2.

**Comment by siom79** [comment]
Fixed with the latest commit. Is available with the next release.
