### ISSUE TITLE
False alarm: METHOD_NO_LONGER_VARARGS

### ISSUE THREAD

**Issue by He-Pin** [siom79/japicmp#393]
version:
0.20.0

The method is there, so this is a false alarm.

Reproduce progress:
1. check out netty/netty 4.1 branch
2. change the japicmp version to 0.20.0
3. run japicmp check

Thanks for this great plugin, I find this when preparing a pr in: https://github.com/netty/netty/pull/13989

**Comment by siom79** [comment]
Thanks for reporting.

The issues looks a bit weird. When debugging, it shows that in [this](https://github.com/siom79/japicmp/blob/59467d292560d4583884ea42c691bf90992594d1/japicmp/src/main/java/japicmp/model/JApiBehavior.java#L373) line in the method `extractVarargsModifier()` the javassist library returns for `behavior.getModifiers()` the value 9 for the old version and 137 for the new version. And 137 & 128 means, that VARARGS is set in the new version but not in the old one. So from the point of japicmp it seems to be correct.

But if you compare both class files `Unpooled.class`, they are identical on each bit. So why does javassist read the value 9 in the old version and 137 in the new version?

**Comment by He-Pin** [comment]
> Thanks for reporting.
> 
> The issues looks a bit weird. When debugging, it shows that in [this](https://github.com/siom79/japicmp/blob/59467d292560d4583884ea42c691bf90992594d1/japicmp/src/main/java/japicmp/model/JApiBehavior.java#L373) line in the method `extractVarargsModifier()` the javassist library returns for `behavior.getModifiers()` the value 9 for the old version and 137 for the new version. And 137 & 128 means, that VARARGS is set in the new version but not in the old one. So from the point of japicmp it seems to be correct.
> 
> But if you compare both class files `Unpooled.class`, they are identical on each bit. So why does javassist read the value 9 in the old version and 137 in the new version?

Thanks for quick validation this, this maybe bump javasist version in later release ?I'm not an expert on this. But I checked 0.15.7, it works.

**Comment by siom79** [comment]
1,5 hours later: There was an issue with matching the corresponding methods in case one method had a byte array as parameter (`byte[]`) and the other one an array of byte arrays with varargs (`byte[]...`). The algorithm did falsely match the wrong arguments (treating `byte[]...` the same as `byte[]`). Therefore, the code comparing the varargs bit in the modifiers did compare two different methods. :-)

I have fixed this with the last commit.

**Comment by siom79** [comment]
Released with 0.21.0.
