### ISSUE TITLE
New option to generate reports in Markdown format `--markdown`

### ISSUE THREAD

**Issue by guillermocalvo** [siom79/japicmp#404]
Currently, japicmp supports generating reports in the following formats:

- XML
- HTML
- Plain text
- Semver

I propose adding a new option `--markdown` to generate reports in [Markdown](https://www.markdownguide.org/) format. This format offers the structured benefits of HTML, while also being human-readable. It is particularly useful for [job summaries in GitHub Actions](https://github.blog/news-insights/product-news/supercharging-github-actions-with-job-summaries/). Additionally, Markdown reports can include ![](https://img.shields.io/badge/badges-8A2BE2) for enhanced visual appeal.

The CLI should generate reports in plain text unless `--markdown` is specified. The Maven plugin should produce reports in all supported formats, including Markdown, resulting in files with the `.md` extension.

**Comment by siom79** [comment]
Hi @guillermocalvo,

I like the idea to create markdown reports, especially together with Github Actions it sounds to be an interesting enhancement.

I have just taken a first look at the implementation and it looks good. 

Currently I am travelling and do not have the time to review everything in detail. But I will do a thorough review as soon as I find enough time for it.

Thanks in advance for this work.

**Comment by guillermocalvo** [comment]
> Currently I am travelling and do not have the time to review everything in detail. But I will do a thorough review as soon as I find enough time for it.

@siom79 I know it's a big PR in terms of files changed. Please take your time and let me know if you'd like to change anything. Thanks for reviewing it!

**Comment by scordio** [comment]
> together with Github Actions it sounds to be an interesting enhancement.

It would be a great fit for the [job summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) feature of GitHub Actions!

**Comment by guillermocalvo** [comment]
Solved by #405
