### ISSUE TITLE
Option to show *only* binary incompatible changes. 

### ISSUE THREAD

**Issue by bondolo** [siom79/japicmp#44]
It would be nice for API compatibility checking to show only the binary incompatible changes. (And trigger failure when incompatibilities are present).

**Comment by siom79** [comment]
Have you tried the option `-b` or `--only-incompatible`?

**Comment by bondolo** [comment]
That option doesn't appear to be available in the Maven plugin. <onlyModified> is available but <onlyIncompatible> isn't provided.

**Comment by siom79** [comment]
Thank you for pull request. It has been merged and released.
