### ISSUE TITLE
unexpected behavior wrt include and exclude packages

### ISSUE THREAD

**Issue by roomsg** [siom79/japicmp#49]
Whenever a package matches an include filter, it is taken into account, ignoring the exclude filter. 
I would have expected the exclude filter has precedence over the include filter

eg:
include: com.example.*
exclude: com.example.internal.*

would ignore all com.example.internal.* packages

**Comment by siom79** [comment]
The idea behind the current implementation is that in most cases you rather want to exclude than include packages. With include being stronger than exclude, you can include subpackages where the base package has been excluded. 

But when users find my implementation counterintuitive, I may have to change it or make it at least configurable.

**Comment by roomsg** [comment]
Well, it's a matter of taste and habit, I guess...
I was expecting to have excludes having precedence over includes, since that is how I am used to work with includes/excludes: "includes" typically defaults to "<all>", "excludes" typically defaults to "<empty>"

Hmm, I started wondering why I was expecting it to be like this, did some googling around and found "some" references:
- ant/maven/gradle are handling it like this 
- other (non-build related) references: jacoco, javadoc, several jenkins plugins, ..

Yet again, a matter of taste/habit, and you're in charge ;-)

**Comment by roomsg** [comment]
BTW: in case you would do changes, I would not make this configurable, you might be "obliged" however for backward compatibility reasons... unless you step up major version...

**Comment by siom79** [comment]
Merged and released.

**Comment by roomsg** [comment]
Thx. Happy to take in new release..
