### ISSUE TITLE
Explicit declaration of dependencies in configuration.

### ISSUE THREAD

**Issue by manikandanrs** [siom79/japicmp#54]
Hi, 

I am trying to use this plugin. I couldn't understand why we need to configure the libraries dependencies under the configuration element. Why can't it pull the dependencies from the pom ?

**Comment by siom79** [comment]
Hi,

there was no other reason than that it was just not implemented. :smirk:

I have added this functionality in the commit above. It will be part of the next release.

**Comment by manikandanrs** [comment]
@siom79 

Thanks for the update.

**Comment by manikandanrs** [comment]
Any clues on when this change will be available in maven ?

**Comment by siom79** [comment]
It is already available: http://search.maven.org/#artifactdetails%7Ccom.github.siom79.japicmp%7Cjapicmp-maven-plugin%7C0.4.1%7Cmaven-plugin. 

```
<dependency>
    <groupId>com.github.siom79.japicmp</groupId>
    <artifactId>japicmp-maven-plugin</artifactId>
    <version>0.4.1</version>
</dependency>
```

**Comment by manikandanrs** [comment]
Thanks again :)
