### ISSUE TITLE
Use separate classpaths for old/new jars

### ISSUE THREAD

**Issue by herkne** [siom79/japicmp#61]
In my opinion it is not correct, to use the same classpath when looking for interfaces or base classes when comparing two classes.

Assume i have a service interface A in a.jar and its implementation B in b.jar. Now i want to compare two versions B1 (in b1.jar) and B2 (in b2.jar) which implement A1 (in a1.jar) and A2 (in a2.jar) which may or may not differ. So for correct results when loading B1 i need a1.jar on the classpath as for loading B2 i need a2.jar.

**Comment by siom79** [comment]
Yes, you are right. This point has been on my list for some time. I will tackle it as soon as I find some time for it.

**Comment by siom79** [comment]
Released with version 0.6.0.
