### ISSUE TITLE
Binary compatibility of a bunch of jars

### ISSUE THREAD

**Issue by veelenga** [siom79/japicmp#67]
Tool is great. No, it is just awesome. Thanks. :+1: 

Our team consider to use japicmp to automate a binary compatibility verification of a bunch of jars. We deliver 15 jars and i can run appropriate command 15 times but the problem is with reporting. We would like to have one html (instead of 15) for a hole verification.

I found few examples for comparison of one jar (with old version). But are there any practices to compare a bunch of jars and report properly ?

Thank you.

**Comment by siom79** [comment]
Thank you for the compliment. :blush:

Currently japicmp does not support the provision of a bunch of jars. But I think that this could be a nice new feature. I know that the `Apache Maven Javadoc Plugin` provides a special goal [aggregate](https://maven.apache.org/plugins/maven-javadoc-plugin/aggregate-mojo.html) that allows to assemble one javadoc documentation for an aggregator project. Something similar would be nice for japicmp.

**Comment by veelenga** [comment]
Yes, it would be awesome. Probably i will be able to help.

I will close this issue as it was on consultation purpose. Could you please create new one like a feature request or something like that ?

Thanks.

**Comment by siom79** [comment]
As there are no different types of tickets (feature request is just a label), I will reopen this one. Your description shows very clearly the motivation for this feature.

**Comment by siom79** [comment]
Released with 0.6.0.

**Comment by veelenga** [comment]
Awesome! Thanks
