### ISSUE TITLE
Have maven 3.0.5 as a prerequisite instead of 3.1.0

### ISSUE THREAD

**Issue by 243826** [siom79/japicmp#70]
3.0.5 of maven is prevalent with many projects and is being widely used. e.g. netbeans 8.0.1 gets shipped with maven 3.0.5. There is an inertia which prevents upgrades without benefits.

While evealuating japicmp, I realized that even if the prerequisite is 3.0.5, japicmp works as probably the API japicmp cares about has not changed.

Can we make 3.0.5 prerequisite? The issues that come with taking such a case will be the cost people who stick to 3.0.5 will have to pay.

**Comment by siom79** [comment]
Released with [0.5.3](https://github.com/siom79/japicmp/releases/tag/japicmp-base-0.5.3).

**Comment by 243826** [comment]
Great! Thank you so much for accepting both the patches and making a release as well :+1:
