### ISSUE TITLE
The build breaks on missing old version.

### ISSUE THREAD

**Issue by georgeyanev** [siom79/japicmp#74]
Shouldn't there be an option (in maven plugin also) for not breaking the build when old-version is missing?

**Comment by siom79** [comment]
What exactly is your use case when the old version is missing? What changes do you want to evaluate?

**Comment by 243826** [comment]
Not sure but the 2 builds are the requirement for comparison. Are you
requesting that instead failing the validation - you want it to succeed
when one of the builds is missing?

--
Chetan

**Comment by georgeyanev** [comment]
Lets say I have just cloned a project with configured japicmp maven plugin. Part of this project is a library which is tracked by japicmp. The plugin is configured to compare the current version against the previous (old version). Since I don't have any older versions of the library my build breaks. I have to either disable the plugin or set the old version to current one in order the build to succeed.

**Comment by siom79** [comment]
But why don't you have the old version? If you deploy a released version of an artifact properly to your company's repository (or even maven's central repository) it is always there.

**Comment by georgeyanev** [comment]
OK, but lets say I am new to the project and I want just to build my recently cloned copy. I expect that after 'git clone' I could issue 'mvn clean install' without any problems and yet there are some more steps I must complete when there should not be any.

**Comment by siom79** [comment]
But the root cause for this problem is that the old version is not available. Your maven build would also fail if this old version would be a dependency that ist not available.
Another option for you is to put the japicmp plug in into a maven profile. Then you can activate the profile only when the old version is available.
