### ISSUE TITLE
[maven plugin] breakBuildOnBinaryIncompatibleModifications Question or bug ?

### ISSUE THREAD

**Issue by LasneF** [siom79/japicmp#93]
hello 

may be i do not get what the exact meaning of the option 
breakBuildOnBinaryIncompatibleModifications=yes

i ve my old version containing X classes , and new version containing X+1 classes 
all are 100 % the same but not the +1 for sure that exits only on the newest version

this use cases is considers as binary incompatible and break my build, 
whereas an application are 100 % that uses just X works as a charm 

may be i is linked to other paramters here is my maven config
```
         <accessModifier>public</accessModifier>
         <onlyModified>true</onlyModified>
         <breakBuildOnModifications>true</breakBuildOnModifications>
          <breakBuildOnBinaryIncompatibleModifications>true</breakBuildOnBinaryIncompatibleModifications>
         <onlyBinaryIncompatible>false</onlyBinaryIncompatible>
         <includeSynthetic>false</includeSynthetic>
         <ignoreMissingClasses>false</ignoreMissingClasses>
         <skipPomModules>true</skipPomModules>
```

**Comment by siom79** [comment]
The point here is the following configuration option:
```
<breakBuildOnModifications>true</breakBuildOnModifications>
```
Setting the option `breakBuildOnModifications` means that the build breaks if you have any kind of modification (removal, addition, changes). This option has nothing to do with binary compatibility. Setting this option to `false` should resolve your issue.

If the build should only fail in case of binary incompatible changes, it is enough to set `breakBuildOnBinaryIncompatibleModifications` to true.

**Comment by LasneF** [comment]
thx for the clarification

**Comment by LasneF** [comment]
i ve digged a little bit more the setting and i am still puzzled 

according to the last comment i ve put this in maven 
```
<parameter>
    <accessModifier>public</accessModifier>
    <onlyModified>true</onlyModified>
    <breakBuildOnModifications>false</breakBuildOnModifications>
      <breakBuildOnBinaryIncompatibleModifications>true</breakBuildOnBinaryIncompatibleModifications>
     <onlyBinaryIncompatible>false</onlyBinaryIncompatible>
     <includeSynthetic>false</includeSynthetic>
     <ignoreMissingClasses>false</ignoreMissingClasses>
     <skipPomModules>true</skipPomModules>
</parameter>
```

despite the setting **breakBuildOnBinaryIncompatibleModifications**  when i add a method on an  an interface it does not break the build the diff says 
***  MODIFIED INTERFACE: PUBLIC ABSTRACT com.trmsys.cargo.akka.IActorSystemFactory  (not serializable)
	+++  NEW METHOD: PUBLIC(+) ABSTRACT(+) akka.actor.ActorRefFactory newActorFactory(int)

and semantic versionning says 0.1.0  i would have assume that it goes to    

so either it is a bug either ... i do not get the paramerters managemen

**Comment by siom79** [comment]
Believe it or not, but adding methods to an interface does not break *binary* compatibility (see [here](https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html#jls-13.5.3)). The reason is that the new method is not referenced in compiled binaries that use your library.

It only breaks *source* compatibility. But currently there is not flag to break the build on source compatibilities. See also discussion on this issue [here](https://github.com/siom79/japicmp/issues/59).

**Comment by LasneF** [comment]
ok , i get the point about JLS , so yes what i would  required is *source* compatibility , 
at least as a basic level such as the interface paradigm (adding a method breaks the compile of the client, and not if a default implementation) 

but that is true that for a consumer point of view if i "receive" an interface i do not bother if a new method is added or not , it is only if i implement the interface that i have to take care. 

may be we could set yet another parameter for interface modification management ?

**Comment by LasneF** [comment]
this would means add a parameter like breakOnInterfaceChange and a modification in 
JApiClass.computeMethodChanges , 

on interface, in javaassist the methods ctMethod.isEmpty() return false when a default methods exist 

do you thing it is a valuable feature or should i do that in a fork ?

**Comment by siom79** [comment]
I think japicmp should also evaluate *source* compatibility in the near futuer. Maybe with version 0.7.0. But this should be addressed  in a more generic way in order to cover also other aspects of *source* compatiblity.

**Comment by LasneF** [comment]
ok, this make sens , i will do this in my local fork  waiting for the 0.7  and then get back to the original one :)
