### ISSUE TITLE
[maven plugin] break if old does not exist

### ISSUE THREAD

**Issue by LasneF** [siom79/japicmp#94]
hello 
i am configuring japicmp at my top pom like this
```
<configuration>
                    <oldVersion>
                        <dependency>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                            <version>3.0.0.RELEASE</version>
                        </dependency>
                    </oldVersion>
                    <newVersion>
                        <dependency>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                            <version>${project.version}</version>
                        </dependency>
                    </newVersion>
```

the point is on my newer version , i have added one module , and it tries to compare with something that was not existing ... that is normal as it is a new artifact  so old version does not exit. But this should not leads to 

```
 Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.6.2-SNAPSHOT:cmp (default) on project cargo-examples-dummy: Could not resolve com.trmsys.cargo.examples:cargo-examples-dummy:jar:3.0.0.RELEASE -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.6.2-SNAPSHOT:cmp (default) on project cargo-examples-dummy: Could not resolve com.trmsys.cargo.examples:cargo-examples-dummy:jar:3.0.0.RELEASE

Caused by: org.apache.maven.plugin.MojoFailureException: Could not resolve com.trmsys.cargo.examples:cargo-examples-dummy:jar:3.0.0.RELEASE
	at japicmp.maven.JApiCmpMojo.resolveArtifact(JApiCmpMojo.java:

 ```

This should leads to report all content of the new jar to new or skip , but not fail the build

**Comment by siom79** [comment]
Have you tried the option `skip` (explained [here](http://siom79.github.io/japicmp/MavenPlugin.html)) in your new artifact?

I let the build fail because I am using in this project the ["fail fast"](https://en.wikipedia.org/wiki/Fail-fast) way. But maybe it makes sense to add an option `notBreakBuildIfArtifactMissing`

**Comment by siom79** [comment]
As issue [#92](https://github.com/siom79/japicmp/issues/92) shows it really makes sense to add an option that allows users to ignore non-resolvable artifacts. Hence I have just committed a change set that adds the new option `ignoreNonResolvableArtifacts` to the maven artifact.

If you like, you can try it out:
```
git clone https://github.com/siom79/japicmp.git
cd japicmp
git checkout develop
mvn clean install
```

**Comment by LasneF** [comment]
this works then,
it becomes no more a blocker. 
i would rather create a report with setting new rather than full skipping 

you re the boss i let you choose

**Comment by siom79** [comment]
I have implemented it exactly this way, i.e. non-resolveable artifacts are ignored and hence the report will be created but reports that everything is new.

**Comment by LasneF** [comment]
, i may open one or two tickets no more but i am closed to put your job in "production" 
thx for yor job, and your quick answer
